package dev.dubhe.anvilcraft.api.tooltip;

import com.google.common.collect.Maps;
import dev.dubhe.anvilcraft.init.block.ModBlocks;
import dev.dubhe.anvilcraft.init.item.ModFoodItems;
import dev.dubhe.anvilcraft.init.item.ModItemTags;
import dev.dubhe.anvilcraft.init.item.ModItems;
import net.minecraft.ChatFormatting;
import net.minecraft.client.resources.language.I18n;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;

import java.util.Collections;
import java.util.Map;
import java.util.function.Consumer;

public class ItemTooltipManager {
    public static final Component SHIFT_TIP = Component.translatable(
        "tooltip.anvilcraft.press_key",
        Component.literal("Shift").withStyle(ChatFormatting.WHITE)
    ).withStyle(ChatFormatting.DARK_GRAY);
    private static final Map<Item, String> NORMAL = Maps.newHashMap();
    private static final Map<Item, String> SHIFT = Maps.newHashMap();

    static {
        ItemTooltipManager.NORMAL.put(ModItems.MAGNET.get(), "Attract surrounding items when use");
        ItemTooltipManager.NORMAL.put(ModItems.GEODE.get(), "Find the surrounding Amethyst Geode when using it");
        ItemTooltipManager.NORMAL.put(ModItems.ANVIL_HAMMER.get(), "It's a hammer, an anvil, a wrench, goggles, and a mace");
        ItemTooltipManager.NORMAL.put(ModItems.ROYAL_ANVIL_HAMMER.get(), "It's a hammer, an anvil, a wrench, goggles, and a mace");
        ItemTooltipManager.NORMAL.put(ModItems.EMBER_ANVIL_HAMMER.get(), "It's a hammer, an anvil, a wrench, goggles, and a mace");
        ItemTooltipManager.NORMAL.put(ModItems.FROST_ANVIL_HAMMER.get(), "It's a hammer, an anvil, a wrench, goggles, and a mace");
        ItemTooltipManager.NORMAL.put(ModItems.TRANSCENDENCE_ANVIL_HAMMER.get(), "It's a hammer, an anvil, a wrench, goggles, and a mace");
        ItemTooltipManager.NORMAL.put(ModBlocks.CURSED_GOLD_BLOCK.asItem(), "Carriers will be cursed");
        ItemTooltipManager.NORMAL.put(ModItems.CURSED_GOLD_INGOT.get(), "Carriers will be cursed");
        ItemTooltipManager.NORMAL.put(ModItems.CURSED_GOLD_NUGGET.get(), "Carriers will be cursed");
        ItemTooltipManager.NORMAL.put(ModItems.TOPAZ.get(), "Containing the power of lightning");
        ItemTooltipManager.NORMAL.put(ModItems.RUBY.get(), "Containing the power of fire");
        ItemTooltipManager.NORMAL.put(ModItems.SAPPHIRE.get(), "Containing the power of frost");
        ItemTooltipManager.NORMAL.put(ModBlocks.RESIN_BLOCK.asItem(), "Use to capture friendly or weak hostile creatures LivingEntity");
        ItemTooltipManager.NORMAL.put(ModBlocks.CRAB_TRAP.asItem(), "Placing it in the water to help you catch aquatic products");
        ItemTooltipManager.NORMAL.put(ModItems.CRAB_CLAW.get(), "Increase touch length when holding");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.ROYAL_ANVIL.asItem(), """
                Never triggers Too Expensive
                Explosion proof, does not degrade from falling""");
        ItemTooltipManager.NORMAL.put(ModBlocks.ROYAL_GRINDSTONE.asItem(), "Removes curses and enchantment penalties, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.ROYAL_SMITHING_TABLE.asItem(), "Does not consume Smithing Templates, Explosion proof");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.TRANSCENDENCE_SMITHING_TABLE.asItem(),
            "Performs all smithing operations without physical templates\nExplosion, Wither and Ender Dragon proof"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.HEATER.asItem(), "Heating the block above, consumes 16 kW");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.BURNING_HEATER.asItem(), """
                Consume fuel to heat the block above
                Each crafting consumes 240 seconds of burn time"""
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.TRANSMISSION_POLE.asItem(), "Build a power grid with a transmission length of 8");
        ItemTooltipManager.NORMAL.put(ModBlocks.CHARGE_COLLECTOR.asItem(), "Collecting charges to generate power");
        ItemTooltipManager.NORMAL.put(ModBlocks.FE_COLLECTOR.asItem(), "Collecting FE to generate power");
        ItemTooltipManager.NORMAL.put(ModBlocks.POWER_CONVERTER_SMALL.asItem(), "Convert power into FE, consumes 1 kW");
        ItemTooltipManager.NORMAL.put(ModBlocks.POWER_CONVERTER_MIDDLE.asItem(), "Convert power into FE, consumes 16 kW");
        ItemTooltipManager.NORMAL.put(ModBlocks.POWER_CONVERTER_BIG.asItem(), "Convert power into FE, consumes 256 kW");
        ItemTooltipManager.NORMAL.put(ModBlocks.PIEZOELECTRIC_CRYSTAL.asItem(), "Charge generated by an anvil fall on it");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.MAGNET_BLOCK.asItem(),
            "Attracting the anvil below, when pushed and pulled by the piston, causes adjacent copper blocks to generate charges"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.HOLLOW_MAGNET_BLOCK.asItem(),
            "Attracting the anvil below, when pushed and pulled by the piston, causes adjacent copper blocks to generate charges"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.FERRITE_CORE_MAGNET_BLOCK.asItem(),
            "Attracting the anvil below, when pushed and pulled by the piston, causes adjacent copper blocks to generate charges"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.BATCH_CRAFTER.asItem(),
            "Received a redstone signal and crafted all internal items at once, with a power consumption of 4 kW"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.BATCH_CUTTER.asItem(),
            "Received a redstone signal and cut all internal items at once, with a power consumption of 4 kW"
        );
        ItemTooltipManager.NORMAL.put(ModItems.ROYAL_STEEL_INGOT.get(), "A piece of iron infused with gem magic");
        ItemTooltipManager.NORMAL.put(ModBlocks.ROYAL_STEEL_BLOCK.asItem(), "A large block of iron infused with gem magic, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.SMOOTH_ROYAL_STEEL_BLOCK.asItem(), "Royal Steel decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_ROYAL_STEEL_BLOCK.asItem(), "Royal Steel decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_ROYAL_STEEL_PILLAR.asItem(), "Royal Steel decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_ROYAL_STEEL_STAIRS.asItem(), "Royal Steel decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_ROYAL_STEEL_SLAB.asItem(), "Royal Steel decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.TEMPERING_GLASS.asItem(),
            "Royal Steel glass, Explosion proof, No tools required on collect"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.REMOTE_TRANSMISSION_POLE.asItem(), "Build a power grid with a transmission length of 16");
        ItemTooltipManager.NORMAL.put(ModBlocks.HEAVY_IRON_BLOCK.asItem(), "Heavy Iron block, highly compressed iron, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.POLISHED_HEAVY_IRON_BLOCK.asItem(), "Heavy Iron decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.POLISHED_HEAVY_IRON_SLAB.asItem(), "Heavy Iron decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.POLISHED_HEAVY_IRON_STAIRS.asItem(), "Heavy Iron decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_HEAVY_IRON_BLOCK.asItem(), "Heavy Iron decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_HEAVY_IRON_SLAB.asItem(), "Heavy Iron decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_HEAVY_IRON_STAIRS.asItem(), "Heavy Iron decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.HEAVY_IRON_PLATE.asItem(), "Heavy Iron decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.HEAVY_IRON_COLUMN.asItem(), "Heavy Iron decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.HEAVY_IRON_BEAM.asItem(), "Heavy Iron decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.HEAVY_IRON_WALL.asItem(), "Heavy Iron decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.HEAVY_IRON_DOOR.asItem(), "Heavy Iron door, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.HEAVY_IRON_TRAPDOOR.asItem(), "Heavy Iron trapdoor, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.ITEM_COLLECTOR.asItem(), "Adjust power consumption based on range and cooling, from 2kW to 32kW");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.EMBER_ANVIL.asItem(), """
               Enhanced compatibility with a soul seemingly hidden deep within
               Anvil Looting can obtain player-only drops
               Wither proof, does not degrade from falling""");
        ItemTooltipManager.NORMAL.put(ModBlocks.EMBER_GRINDSTONE.asItem(), "Extracts enchantments onto books, Wither proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.EMBER_SMITHING_TABLE.asItem(), "All-in-one combination smithing, Wither proof");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.EMBER_METAL_BLOCK.asItem(),
            "A large block of heat-resistant Netherite tempered in fire for eons, Wither proof"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.EMBER_GLASS.asItem(),
            "Ember Metal glass, Wither proof, No tools required on collect"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_EMBER_METAL_BLOCK.asItem(), "Ember Metal decorative block, Wither proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_EMBER_METAL_PILLAR.asItem(), "Ember Metal decorative block, Wither proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_EMBER_METAL_SLAB.asItem(), "Ember Metal decorative block, Wither proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_EMBER_METAL_STAIRS.asItem(), "Ember Metal decorative block, Wither proof");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.OVERHEATED_EMBER_METAL_BLOCK.asItem(), """
                Extreme heat has broken its mass-energy balance; injecting mass will transform it into Transcendium
                May degrade into Netherite upon cooling""");
        ItemTooltipManager.NORMAL.put(ModItems.EMBER_METAL_INGOT.get(), "A piece of heat-resistant Netherite tempered in fire for eons");
        ItemTooltipManager.NORMAL.put(ModItems.FROST_METAL_INGOT.get(), "A piece of cold-resistant Royal Steel tempered in extreme cold for eons");
        ItemTooltipManager.NORMAL.put(ModItems.MAGNET_INGOT.get(), "A magnetized iron ingot");
        ItemTooltipManager.NORMAL.put(ModItems.TUNGSTEN_INGOT.get(), "A heat-resistant and dense metal, material for Ancient Debris");
        ItemTooltipManager.NORMAL.put(ModBlocks.TUNGSTEN_BLOCK.asItem(), "A large block of heat-resistant, high-density metal that can be heated to extreme temperatures");
        ItemTooltipManager.NORMAL.put(ModItems.TITANIUM_INGOT.get(), "A strong and lightweight metal");
        ItemTooltipManager.NORMAL.put(ModBlocks.TITANIUM_BLOCK.asItem(), "A large block of strong, lightweight metal");
        ItemTooltipManager.NORMAL.put(ModItems.ZINC_INGOT.get(), "A lightweight metal");
        ItemTooltipManager.NORMAL.put(ModBlocks.ZINC_BLOCK.asItem(), "A large block of lightweight metal");
        ItemTooltipManager.NORMAL.put(ModItems.TIN_INGOT.get(), "A soft and corrosion-resistant metal");
        ItemTooltipManager.NORMAL.put(ModBlocks.TIN_BLOCK.asItem(), "A large block of soft, corrosion-resistant metal");
        ItemTooltipManager.NORMAL.put(ModItems.LEAD_INGOT.get(), "A dense and heavy metal");
        ItemTooltipManager.NORMAL.put(ModBlocks.LEAD_BLOCK.asItem(), "A large block of dense, heavy metal that absorbs radiation and slows the decay of radioactive blocks");
        ItemTooltipManager.NORMAL.put(ModItems.SILVER_INGOT.get(), "A highly reflective metal");
        ItemTooltipManager.NORMAL.put(ModBlocks.SILVER_BLOCK.asItem(), "A large block of highly reflective metal");
        ItemTooltipManager.NORMAL.put(ModItems.URANIUM_INGOT.get(), "Radioactive - handle with care");
        ItemTooltipManager.NORMAL.put(ModBlocks.URANIUM_BLOCK.asItem(), "A large block of radioactive material that continuously releases heat but decays when multiple blocks are adjacent");
        ItemTooltipManager.NORMAL.put(
            ModItems.PLUTONIUM_INGOT.get(),
            "Highly radioactive - cannot be mined naturally, obtained from uranium transmutation"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.PLUTONIUM_BLOCK.asItem(),
            "A large block of highly radioactive material obtained only by transmuting uranium; continuously releases heat but decays when multiple blocks are adjacent"
        );
        ItemTooltipManager.NORMAL.put(ModItems.BRONZE_INGOT.get(), "A durable copper-tin alloy");
        ItemTooltipManager.NORMAL.put(ModBlocks.BRONZE_BLOCK.asItem(), "A large block of durable copper-tin alloy");
        ItemTooltipManager.NORMAL.put(ModItems.BRASS_INGOT.get(), "A corrosion-resistant copper-zinc alloy");
        ItemTooltipManager.NORMAL.put(ModBlocks.BRASS_BLOCK.asItem(), "A large block of corrosion-resistant copper-zinc alloy");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_BRONZE_BLOCK.asItem(), "Bronze decorative block");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_BRONZE_STAIRS.asItem(), "Bronze decorative block");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_BRONZE_SLAB.asItem(), "Bronze decorative block");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_BRONZE_PILLAR.asItem(), "Bronze decorative block");
        ItemTooltipManager.NORMAL.put(ModBlocks.CHISELED_BRONZE_BLOCK.asItem(), "Bronze decorative block");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_BRASS_BLOCK.asItem(), "Brass decorative block");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_BRASS_STAIRS.asItem(), "Brass decorative block");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_BRASS_SLAB.asItem(), "Brass decorative block");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_BRASS_PILLAR.asItem(), "Brass decorative block");
        ItemTooltipManager.NORMAL.put(ModBlocks.CHISELED_BRASS_BLOCK.asItem(), "Brass decorative block");
        ItemTooltipManager.NORMAL.put(ModItems.ROYAL_STEEL_NUGGET.get(), "A small piece of iron infused with gem magic");
        ItemTooltipManager.NORMAL.put(ModItems.EMBER_METAL_NUGGET.get(), "A small piece of heat-resistant Netherite tempered in fire for eons");
        ItemTooltipManager.NORMAL.put(ModItems.FROST_METAL_NUGGET.get(), "A small piece of cold-resistant Royal Steel tempered in extreme cold for eons");
        ItemTooltipManager.NORMAL.put(ModItems.TUNGSTEN_NUGGET.get(), "A small piece of heat-resistant, high-density metal");
        ItemTooltipManager.NORMAL.put(ModItems.TITANIUM_NUGGET.get(), "A small piece of Titanium");
        ItemTooltipManager.NORMAL.put(ModItems.ZINC_NUGGET.get(), "A small piece of Zinc");
        ItemTooltipManager.NORMAL.put(ModItems.TIN_NUGGET.get(), "A small piece of Tin");
        ItemTooltipManager.NORMAL.put(ModItems.LEAD_NUGGET.get(), "A small piece of Lead");
        ItemTooltipManager.NORMAL.put(ModItems.SILVER_NUGGET.get(), "A small piece of Silver");
        ItemTooltipManager.NORMAL.put(ModItems.URANIUM_NUGGET.get(), "A small piece of Uranium");
        ItemTooltipManager.NORMAL.put(ModItems.PLUTONIUM_NUGGET.get(), "A small piece of highly radioactive material obtained only by transmuting uranium");
        ItemTooltipManager.NORMAL.put(ModItems.BRONZE_NUGGET.get(), "A small piece of durable copper-tin alloy");
        ItemTooltipManager.NORMAL.put(ModItems.BRASS_NUGGET.get(), "A small piece of corrosion-resistant copper-zinc alloy");
        ItemTooltipManager.NORMAL.put(ModItems.TIN_CAN.asItem(), "Tin cans can be combined with any food to obtain canned food");
        ItemTooltipManager.NORMAL.put(ModFoodItems.CANNED_FOOD.asItem(), "Stackable instant food");
        ItemTooltipManager.NORMAL.put(ModItems.IONOCRAFT.asItem(), "It will float when placed in the power grid");
        ItemTooltipManager.NORMAL.put(ModItems.LEVITATION_POWDER.asItem(), "Slight weightlessness");
        ItemTooltipManager.NORMAL.put(ModItems.NEGATIVE_MATTER.asItem(), "Negative matter is not antimatter, it is anti gravity matter");
        ItemTooltipManager.NORMAL.put(ModItems.NEGATIVE_MATTER_NUGGET.asItem(), "Negative matter is not antimatter, it is anti gravity matter");
        ItemTooltipManager.NORMAL.put(ModBlocks.NEGATIVE_MATTER_BLOCK.asItem(), "Negative matter is not antimatter, it is anti gravity matter");
        ItemTooltipManager.NORMAL.put(ModItems.NEUTRONIUM_INGOT.asItem(), "Pass through most blocks except end dust, negative matter block, and bedrock");
        ItemTooltipManager.NORMAL.put(ModItems.STABLE_NEUTRONIUM_INGOT.asItem(), "No more passing through blocks");
        ItemTooltipManager.NORMAL.put(
            ModItems.CHARGED_NEUTRONIUM_INGOT.asItem(),
            "No longer passing through blocks, storing a large amount of electrical energy"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.TESLA_TOWER.asItem(),
            "Shocks mobs or lightning rods within 8 blocks, consumes 128 kW"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.ACTIVE_SILENCER.asItem(), "Eliminate selected nearby sounds");
        ItemTooltipManager.NORMAL.put(ModBlocks.COPPER_PRESSURE_PLATE.asItem(), "Redstone signal increases with pressing time, also a copper plate");
        ItemTooltipManager.NORMAL.put(ModBlocks.EXPOSED_COPPER_PRESSURE_PLATE.asItem(), "Redstone signal increases with pressing time, also a copper plate");
        ItemTooltipManager.NORMAL.put(ModBlocks.WEATHERED_COPPER_PRESSURE_PLATE.asItem(), "Redstone signal increases with pressing time, also a copper plate");
        ItemTooltipManager.NORMAL.put(ModBlocks.OXIDIZED_COPPER_PRESSURE_PLATE.asItem(), "Redstone signal increases with pressing time, also a copper plate");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.ZINC_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the highest percentage of health of the mobs above, also a zinc plate"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.TIN_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the lowest percentage of health of the mobs above, also a tin plate"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.LEAD_PRESSURE_PLATE.asItem(),
            "Output redstone signal based on the number of mob species above, also a lead plate"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.SILVER_PRESSURE_PLATE.asItem(),
            "Output redstone signal based on the number of undead mobs above, also a silver plate"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.TUNGSTEN_PRESSURE_PLATE.asItem(),
            "Output redstone signal based on the number of fire-resistant entities above, also a tungsten plate"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.TITANIUM_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the highest durability of the items above, also a titanium plate"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.URANIUM_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the lowest durability of the items above, also a uranium plate"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.PLUTONIUM_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the player in hand item durability, also a plutonium plate"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.BRONZE_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on player satiety above, also a bronze plate"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.BRASS_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the inventory's filling degree of player above, also a brass plate"
        );
        ItemTooltipManager.NORMAL.put(ModItems.MULTITOOL_ITEM.get(), "Press [Alt] to switch tool modes");
        ItemTooltipManager.NORMAL.put(ModItems.SPECTRAL_SLINGSHOT.get(), "Load a weapon to fire its phantom");
        ItemTooltipManager.NORMAL.put(ModItems.RECOVERY_PEARL.get(), "Right-click to teleport to last death point");
        ItemTooltipManager.NORMAL.put(ModBlocks.HEAT_COLLECTOR.asItem(), "Generates power from heat");
        ItemTooltipManager.NORMAL.put(ModBlocks.VOID_ENERGY_COLLECTOR.asItem(), "Generates power from Void energy");
        ItemTooltipManager.NORMAL.put(ModBlocks.RUBY_LASER.asItem(), "Emits a laser beam when powered");
        ItemTooltipManager.NORMAL.put(ModBlocks.RUBY_PRISM.asItem(), "Deflects or converges laser beams");
        ItemTooltipManager.NORMAL.put(ModBlocks.TRANSPARENT_CRAFTING_TABLE.asItem(), "Aesthetic, connectable Crafting Table");
        ItemTooltipManager.NORMAL.put(ModBlocks.MENGER_SPONGE.asItem(), "Absorbs infinite liquid");
        ItemTooltipManager.NORMAL.put(ModBlocks.SLIDING_RAIL.asItem(), "Frictionless surface for sliding entities and even blocks");
        ItemTooltipManager.NORMAL.put(ModBlocks.POWERED_SLIDING_RAIL.asItem(), "Accelerates items, entities, or blocks when powered");
        ItemTooltipManager.NORMAL.put(ModBlocks.DETECTOR_SLIDING_RAIL.asItem(), "Output signal when objects or blocks slide over");
        ItemTooltipManager.NORMAL.put(ModBlocks.ACTIVATOR_SLIDING_RAIL.asItem(), "Activates blocks sliding over it");
        ItemTooltipManager.NORMAL.put(ModBlocks.SLIDING_RAIL_STOP.asItem(), "Stops sliding items, entities, or blocks");
        ItemTooltipManager.NORMAL.put(ModBlocks.PROPEL_PISTON.asItem(), "Integrated piston worm, requires Capacitor or Laser power");
        ItemTooltipManager.NORMAL.put(ModBlocks.PULSE_GENERATOR.asItem(), "Customizes pulse delay and duration");
        ItemTooltipManager.NORMAL.put(ModBlocks.ADVANCED_COMPARATOR.asItem(), "Supports Hysteresis and Window comparison modes");
        ItemTooltipManager.NORMAL.put(ModItems.EMERALD_AMULET.get(), "Grants Hero of the Village");
        ItemTooltipManager.NORMAL.put(ModItems.TOPAZ_AMULET.get(), "Grants immunity to lightning damage");
        ItemTooltipManager.NORMAL.put(ModItems.RUBY_AMULET.get(), "Grants Fire Resistance");
        ItemTooltipManager.NORMAL.put(ModItems.SAPPHIRE_AMULET.get(), "Grants Conduit Power");
        ItemTooltipManager.NORMAL.put(ModItems.ANVIL_AMULET.get(), "Grants immunity to anvil damage");
        ItemTooltipManager.NORMAL.put(ModItems.FEATHER_AMULET.get(), "Grants immunity to fall damage");
        ItemTooltipManager.NORMAL.put(ModItems.CAT_AMULET.get(), "Scares away Creepers and Phantoms");
        ItemTooltipManager.NORMAL.put(ModItems.DOG_AMULET.get(), "Scares away Skeletons");
        ItemTooltipManager.NORMAL.put(ModItems.SILENCE_AMULET.get(), "Silences the wearer");
        ItemTooltipManager.NORMAL.put(
            ModItems.ABNORMAL_AMULET.get(),
            "Prevents damage from carrying Uranium, Plutonium, Floating Powder, Cursed Gold items"
        );
        ItemTooltipManager.NORMAL.put(ModItems.NATURE_AMULET.get(), "Combines Silence, Cat, Dog, and Feather Amulet effects");
        ItemTooltipManager.NORMAL.put(ModItems.GEM_AMULET.get(), "Combines effects of all four Gem Amulets");
        ItemTooltipManager.NORMAL.put(ModItems.CAPACITOR.asItem(), "8 MFE stored");
        ItemTooltipManager.NORMAL.put(ModItems.CAPACITOR_EMPTY.asItem(), "8 MFE capacity");
        ItemTooltipManager.NORMAL.put(ModItems.SUPER_CAPACITOR.asItem(), "160 MFE stored");
        ItemTooltipManager.NORMAL.put(ModItems.SUPER_CAPACITOR_EMPTY.asItem(), "160 MFE capacity");
        ItemTooltipManager.NORMAL.put(ModItems.HEAVY_HALBERD_CORE.get(), "Material for crafting the Heavy Halberd");
        ItemTooltipManager.NORMAL.put(ModItems.RESONATOR_CORE.get(), "Material for crafting the Resonator");
        ItemTooltipManager.NORMAL.put(ModBlocks.BLACK_HOLE.asItem(), "Dev Block with intense gravitational attraction");
        ItemTooltipManager.NORMAL.put(ModBlocks.WHITE_HOLE.asItem(), "Dev Block with intense gravitational repulsion");
        ItemTooltipManager.NORMAL.put(ModBlocks.CHARGER.asItem(), "Charges items, supports manual or automated input");
        ItemTooltipManager.NORMAL.put(ModBlocks.DISCHARGER.asItem(), "Discharges capacitors, supports manual or automated input");
        ItemTooltipManager.NORMAL.put(ModBlocks.LASER_RECEIVER.asItem(), "Receives lasers, generating power and a redstone signal based on the laser level");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.FROST_ANVIL.asItem(), """
                Slower enchantment penalty growth, repairs any item with Frost Metal, free renaming
                Explosion proof, does not degrade from falling"""
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.TRANSCENDENCE_ANVIL.asItem(), """
                Ignores enchantment level limits, and Anvil Looting produces additional drops
                Immune to most destruction methods, does not degrade from falling""");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.TRANSCENDENCE_GRINDSTONE.asItem(),
            """
                Removes curses and enchantment penalties, selectively removes or transfers multiple enchantments
                Immune to most destruction methods"""
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.TRANSCENDENCE_DECO_BLOCK.asItem(),
            "Transcendium decorative block; its low Transcendium content means it is not indestructible"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.TRANSCENDENCE_DECO_OUTLINE.asItem(),
            "Transcendium decorative block; its low Transcendium content means it is not indestructible"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.FROST_GRINDSTONE.asItem(), "Selectively removes individual enchantments, Explosion proof");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.FROST_SMITHING_TABLE.asItem(),
            "Works with Permutation and Deformation smithing templates, Explosion proof"
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.FROST_METAL_BLOCK.asItem(),
            "A large block of cold-resistant Royal Steel tempered in extreme cold for eons, Explosion proof"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.FROST_GLASS.asItem(), "Frost Metal glass, Explosion proof, No tools required on collect");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_FROST_METAL_BLOCK.asItem(), "Frost Metal decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_FROST_METAL_PILLAR.asItem(), "Frost Metal decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_FROST_METAL_SLAB.asItem(), "Frost Metal decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.CUT_FROST_METAL_STAIRS.asItem(), "Frost Metal decorative block, Explosion proof");
        ItemTooltipManager.NORMAL.put(ModBlocks.SPECTRAL_ANVIL.asItem(), "Creates phantom shadows when the upper magnet is demagnetized");
        ItemTooltipManager.NORMAL.put(ModBlocks.BLOCK_PLACER.asItem(), "Places blocks in front when powered by redstone");
        ItemTooltipManager.NORMAL.put(ModItems.STRUCTURE_DISK.get(), "Stores structure data, used in blueprint mode of Smart Block Placer");
        ItemTooltipManager.NORMAL.put(ModBlocks.STRUCTURE_SCANNER.asItem(), "Scans and stores structures in Structure Disk");
        ItemTooltipManager.NORMAL.put(ModBlocks.SMART_BLOCK_PLACER.asItem(), "Advanced block placer with 5x5x5 configurable placement area");
        ItemTooltipManager.NORMAL.put(ModBlocks.FISH_TANK.asItem(), "Used for anvil synthesis and provides underwater breathing when worn");
        ItemTooltipManager.NORMAL.put(ModBlocks.BLOCK_DEVOURER.asItem(), "Breaks 3×3 area of blocks in front when powered by redstone");
        ItemTooltipManager.NORMAL.put(ModBlocks.INDUCTION_LIGHT.asItem(), "Provides lighting and configurable special modes");
        ItemTooltipManager.NORMAL.put(ModBlocks.HELIOSTATS.asItem(), "Heats targeted blocks during the day");
        ItemTooltipManager.NORMAL.put(ModItems.IONOCRAFT_BACKPACK.asItem(), "Allows creative flight while equipped, requires power from the energy grid or capacitors in the inventory");
        ItemTooltipManager.NORMAL.put(ModBlocks.BLOCK_COMPARATOR.asItem(), "Outputs signal when side blocks are the same, right-click to switch to precise state detection mode");
        ItemTooltipManager.NORMAL.put(ModBlocks.ITEM_DETECTOR.asItem(), "Detects specific items behind (drops/containers) to output redstone signal");
        ItemTooltipManager.NORMAL.put(ModBlocks.IMPACT_PILE.asItem(), "Place on Bedrock or Deepslate and strike with falling anvil to create Moneral Fountain");
        ItemTooltipManager.NORMAL.put(ModBlocks.SPACE_OVERCOMPRESSOR.asItem(), "Compresses items into Neutronium Ingots, compresses multiblock outputs into drops");
        ItemTooltipManager.NORMAL.put(ModBlocks.ACCELERATION_RING.asItem(), "Creates acceleration field for anvils, projectiles, or players with Anvil Hammer");
        ItemTooltipManager.NORMAL.put(ModBlocks.DEFLECTION_RING.asItem(), "Deflects passing objects 90°, detect speed with Comparator");
        ItemTooltipManager.NORMAL.put(ModItems.DRAGON_ROD.asItem(), "Portable block devourer with adjustable range");
        ItemTooltipManager.NORMAL.put(ModItems.EMBER_DRAGON_ROD.asItem(), "Portable block devourer with adjustable range");
        ItemTooltipManager.NORMAL.put(ModItems.FROST_DRAGON_ROD.asItem(), "Portable block devourer with adjustable range");
        ItemTooltipManager.NORMAL.put(ModItems.ROYAL_DRAGON_ROD.asItem(), "Portable block devourer with adjustable range");
        ItemTooltipManager.NORMAL.put(ModItems.TRANSCENDENCE_DRAGON_ROD.asItem(), "Portable block devourer with adjustable range");
        ItemTooltipManager.NORMAL.put(ModItems.FILTER.asItem(), "Matches items based on configuration, usable in any filter slot");
        ItemTooltipManager.NORMAL.put(ModItems.TOTEM_OF_RECOVERY.asItem(), "Teleports to spawn on death, grants a Recall Pearl to return to death point");
        ItemTooltipManager.NORMAL.put(ModItems.TOTEM_OF_RAGE.asItem(), "Grants invulnerability and berserk on fatal damage, death is inevitable after 1 minute");
        ItemTooltipManager.NORMAL.put(ModItems.COMRADE_AMULET.asItem(), "Signable by players via right-click, prevents damage from signed players");
        ItemTooltipManager.NORMAL.put(ModItems.PILL_BOX.asItem(), "Store pills for quick use");
        ItemTooltipManager.NORMAL.put(ModItems.AMULET_BOX.asItem(), "Stores multiple active amulets or totems");
        ItemTooltipManager.NORMAL.put(ModBlocks.CELESTIAL_FORGING_ANVIL.asItem(), "Forge celestial bodies, build megastructures");
        ItemTooltipManager.NORMAL.put(ModItems.PIPE.get(), "Transports fluids between containers, gravity-driven flow");
        ItemTooltipManager.NORMAL.put(ModItems.TRANSCENDIUM_INGOT.get(), "A piece of strong-interaction matter sustained by magic, immune to most forms of destruction");
        ItemTooltipManager.NORMAL.put(ModBlocks.TRANSCENDIUM_BLOCK.asItem(), "A large block of strong-interaction matter sustained by magic, immune to most forms of destruction");
        ItemTooltipManager.NORMAL.put(ModItems.TRANSCENDIUM_NUGGET.get(), "A small piece of strong-interaction matter sustained by magic, immune to most forms of destruction");
        ItemTooltipManager.NORMAL.put(ModItems.VOID_MATTER.get(), "The primordial substance that creates all things, mined from the void, decays outside the void");
        ItemTooltipManager.NORMAL.put(ModItems.EXCITED_STATE_VOID_MATTER.get(), "The substance of black hole singularities, more unstable than ordinary void matter");
        ItemTooltipManager.NORMAL.put(ModItems.EARTH_CORE_SHARD.get(), "A fragment of a planet's heart, pulsing with geological might");
        ItemTooltipManager.NORMAL.put(
            ModItems.MULTIPHASE_MATTER.get(),
            "Matter that exists in multiple stable phases simultaneously, switchable under special conditions"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.OVERSEER.asItem(), "Chunk loader that works on suitable base");
        ItemTooltipManager.NORMAL.put(ModBlocks.PUMP.asItem(), "Pumps fluids, consumes 32 kW");
        ItemTooltipManager.NORMAL.put(ModBlocks.CREATIVE_CRATE.asItem(), "Infinite item storage and supply");
        ItemTooltipManager.NORMAL.put(ModBlocks.CREATIVE_FLUID_TANK.asItem(), "Infinite fluid storage and supply");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.FLUID_TANK.asItem(),
            """
                Stores 16B of fluid; Menger Sponges expand it to 12800B and make it infinite when full
                Can interact with Dispensers for fluid transfer"""
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.LARGE_FLUID_TANK.asItem(),
            """
                Stores 512B shared by any number of fluids
                Menger Sponges unlock unlimited total storage
                Can store multiple fluids, each type of fluid that reaches 12800B will be converted to infinite
                Can interact with Dispensers for fluid transfer"""
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.DRAIN.asItem(), "Transfers fluid vertically, outputting downward and drawing from above");
        ItemTooltipManager.NORMAL.put(ModBlocks.REDSTONE_WIRE.asItem(), "Transmit redstone signals more precisely");
        ItemTooltipManager.NORMAL.put(ModBlocks.TRADING_STATION.asItem(), "Trading platform for players and villagers");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.CORRUPTED_BEACON.asItem(),
            "Releases the wither power within the beacon, its beam accelerates time flow or causes mutations"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.LARGE_CAKE.asItem(), "A cake, a very big cake. 27 bites, each bite fills you up");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.CONFINEMENT_CHAMBER.asItem(),
            "Contains elementary particles and unstable items, keeping them stable"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.CONFINED_TIME_ANVILON.asItem(), "Confinement chamber for time-type Anvilon");
        ItemTooltipManager.NORMAL.put(ModBlocks.CONFINED_SPACE_ANVILON.asItem(), "Confinement chamber for space-type Anvilon");
        ItemTooltipManager.NORMAL.put(ModBlocks.CONFINED_MASS_ANVILON.asItem(), "Confinement chamber for mass-type Anvilon");
        ItemTooltipManager.NORMAL.put(ModBlocks.CONFINED_ENERGY_ANVILON.asItem(), "Confinement chamber for energy-type Anvilon");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.CONFINED_NEUTRONIUM_INGOT_BLOCK.asItem(),
            "A confinement chamber containing a Charged Neutronium Ingot"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.NEUTRON_IRRADIATOR.asItem(), "Performs neutron irradiation recipes, absorbs confined anvilons for block procedural process");
        ItemTooltipManager.NORMAL.put(ModBlocks.CAKE_BASE_BLOCK.asItem(), "A block of cake base, use a shovel as a spoon to eat it");
        ItemTooltipManager.NORMAL.put(ModBlocks.CREAM_BLOCK.asItem(), "A block of cream, use a shovel as a spoon to eat it");
        ItemTooltipManager.NORMAL.put(ModBlocks.BERRY_CREAM_BLOCK.asItem(), "A block of berry cream, use a shovel as a spoon to eat it");
        ItemTooltipManager.NORMAL.put(ModBlocks.CHOCOLATE_CREAM_BLOCK.asItem(), "A block of chocolate cream, use a shovel as a spoon to eat it");
        ItemTooltipManager.NORMAL.put(ModBlocks.CAKE_BLOCK.asItem(), "A block of cream cake, use a shovel as a spoon to eat it");
        ItemTooltipManager.NORMAL.put(ModBlocks.BERRY_CAKE_BLOCK.asItem(), "A block of berry cake, use a shovel as a spoon to eat it");
        ItemTooltipManager.NORMAL.put(ModBlocks.CHOCOLATE_CAKE_BLOCK.asItem(), "A block of chocolate cake, use a shovel as a spoon to eat it");
        ItemTooltipManager.NORMAL.put(ModBlocks.CONTROL_VALVE.asItem(), "Controls the type and flow rate of passing fluids and can be locked by redstone");
        ItemTooltipManager.NORMAL.put(ModBlocks.SPACETIME_SUPERCOMPUTER.asItem(), "Consumes power to run certain time commands");
        ItemTooltipManager.NORMAL.put(ModBlocks.CELESTIAL_FORGING_ANVIL_AMPLIFIER.asItem(), "Amplifies the Celestial Forging Anvil to support larger megastructures");
        ItemTooltipManager.NORMAL.put(ModBlocks.CELESTIAL_FORGING_ANVIL_LOGISTICS_INTERFACE.asItem(), "Item I/O interface for the Celestial Forging Anvil");
        ItemTooltipManager.NORMAL.put(ModBlocks.CELESTIAL_FORGING_ANVIL_FLUID_INTERFACE.asItem(), "Fluid I/O interface for the Celestial Forging Anvil");
        ItemTooltipManager.NORMAL.put(ModBlocks.CELESTIAL_FORGING_ANVIL_LASER_INTERFACE.asItem(), "Laser I/O interface for the Celestial Forging Anvil");
        ItemTooltipManager.NORMAL.put(ModBlocks.CELESTIAL_FORGING_ANVIL_INTERFACE_PLACEHOLDER.asItem(), "Placeholder block for Celestial Forging Anvil structure");
        ItemTooltipManager.NORMAL.put(ModBlocks.CELESTIAL_FORGING_ANVIL_PORTAL.asItem(), "Teleports players and entities between two portals");
        ItemTooltipManager.NORMAL.put(ModBlocks.LENS.asItem(), "Use special glass to enchant lasers");
        ItemTooltipManager.NORMAL.put(ModItems.CHECK_VALVE.get(), "Allows fluid to flow in only one direction");
        ItemTooltipManager.NORMAL.put(
            ModItems.DYSON_SPHERE_COMPONENT.get(),
            "Material for building a Dyson Sphere, used in the Celestial Forging Anvil"
        );
        ItemTooltipManager.NORMAL.put(
            ModItems.PENROSE_SPHERE_COMPONENT.get(),
            "Material for building a Penrose Sphere, used in the Celestial Forging Anvil"
        );
        ItemTooltipManager.NORMAL.put(
            ModItems.MATTER_DECOMPRESSOR_COMPONENT.get(),
            "Material for building a Matter Decompressor, used in the Celestial Forging Anvil"
        );
        ItemTooltipManager.NORMAL.put(
            ModItems.WORMHOLE_STABILIZER_COMPONENT.get(),
            "Material for building a Wormhole Stabilizer, used in the Celestial Forging Anvil"
        );
        ItemTooltipManager.NORMAL.put(
            ModItems.STELLAR_RING_COMPONENT.get(),
            "Material for building a Stellar Ring Collider, used in the Celestial Forging Anvil"
        );
        ItemTooltipManager.NORMAL.put(
            ModItems.MAGNETAR_COIL_COMPONENT.get(),
            "Material for building a Magnetar Coil, used in the Celestial Forging Anvil"
        );
        ItemTooltipManager.NORMAL.put(
            ModItems.STELLAR_EVOLUTION_ACCELERATOR_COMPONENT.get(),
            "Material for building a Stellar Evolution Accelerator, used in the Celestial Forging Anvil"
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.LARGE_LASER.asItem(), "Equivalent to 16 lasers, outputs 16 intensity levels of laser, consumes 256 kW");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.SUGAR_BLOCK.asItem(), """
            A large block of sugar
            Also a piezoelectric crystal, but seems fragile"""
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.FLINT_BLOCK.asItem(), """
            A large block of flint
            When pushed or pulled by a piston, it creates fire around it if an iron block is nearby"""
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.GUNPOWER_BLOCK.asItem(), """
            A large block of gunpowder
            If struck by a falling anvil, it explodes and launches the anvil back up to the height it fell from"""
        );
        ItemTooltipManager.NORMAL.put(
            ModBlocks.ROTTEN_FLESH_BLOCK.asItem(), """
            A large block of rotten flesh
            It cushions fall damage, but landing on it will make you nauseous for 30 seconds
            Can also be smelted into Netherrack"""
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.SINGULARITY_CRYSTAL.asItem(), "Data disk for storing extreme celestial data from the Celestial Forging Anvil");
        ItemTooltipManager.NORMAL.put(ModItems.LASER_GUN.get(), "Hold right-click to consume power and fire a laser that grows increasingly powerful");
        ItemTooltipManager.NORMAL.put(ModItems.CORRUPTED_BEACON_ACTIVATOR.get(), "Hold right-click to consume power and fire a corruption beam");
        ItemTooltipManager.NORMAL.put(ModItems.TESLA_GUN.get(), "Hold right-click to consume power and fire chain lightning that bounces between mobs");
        ItemTooltipManager.NORMAL.put(ModItems.ANVIL_RAILGUN.get(), "Hold right-click to consumes power to charge up and launch a high-speed anvil");
        ItemTooltipManager.NORMAL.put(ModItems.SPECTRAL_SLINGSHOT.get(), "Hold right-click to consume power and fires spectral weapons");
        ItemTooltipManager.NORMAL.put(ModItems.ENERGY_WEAPON_PLATFORM.get(), "640 MFE stored, but will only inherit the result of Energy Weapon Making");
        ItemTooltipManager.NORMAL.put(
            ModBlocks.INFINITE_COLLECTOR.asItem(), """
            Generates power by collecting both heat and charge, no upper power limit
            Provides a baseline output of 256 kW"""
        );
        ItemTooltipManager.NORMAL.put(ModBlocks.LOAD_MONITOR.asItem(), "Monitor the grid load condition, can output a signal by redstone comparator");
        ItemTooltipManager.NORMAL.put(ModBlocks.CHUTE.asItem(), "An advanced Hopper, can transfer a full stack of items at a time");
        ItemTooltipManager.NORMAL.put(ModBlocks.MAGNETIC_CHUTE.asItem(), "An advanced Chute, with the ability to transport items vertically");

        ItemTooltipManager.SHIFT.put(
            ModItems.LASER_GUN.get(), """
                The laser damages mobs and can also mine blocks
                Charging longer increases damage, but watch out for overheating!
                Enchanting the laser gun alters its beam behavior"""
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.CORRUPTED_BEACON_ACTIVATOR.get(), """
                Fires a beam of corruption that pierces through targets, dealing damage and inflicting Wither
                It passes through glass and does not convert mobs
                Enchanting the Corrupted Beacon Exciter boosts the beam's damage"""
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.TESLA_GUN.get(), """
                Fires chain lightning that arcs between up to 4 mobs, dealing reduced damage with each bounce
                The lightning can convert mobs, and lightning rods will also be targeted
                Each strike is followed by a cooldown, which can be shortened by enchanting the Tesla Gun"""
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.ANVIL_RAILGUN.get(), """
                Hold right-click to load an anvil from your offhand into the railgun
                Then hold right-click again to charge up, and release to launch the anvil
                Longer charging results in higher speed and damage
                Enchanting the Anvil Railgun can boost damage, reduce charge time, or change its firing behavior"""
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.SPECTRAL_SLINGSHOT.get(), """
                Hold right-click to load your offhand weapon into the Spectral Slingshot
                Once loaded, right-click again to fire a spectral copy of that weapon, dealing damage
                Each shot has a cooldown, which can be reduced by enchanting the launcher"""
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.ENERGY_WEAPON_PLATFORM.get(), """
                640 MFE stored, but will only inherit the result of Energy Weapon Making
                Can be crafted with different materials to create various energy weapons
                Consumes capacitors to restore power"""
        );

        ItemTooltipManager.SHIFT.put(
            ModItems.CHECK_VALVE.get(), """
                When holding a check valve, right-click one end of a pipe to convert that end into a check valve
                Can remove check valve by right-clicking it while holding a check valve, or with an empty hand
                Supplying a redstone signal reverses the flow direction of the check valve"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.CELESTIAL_FORGING_ANVIL.asItem(), """
                Place an anvil to determine celestial parameters
                Once a suitable celestial body is found, lock it to build a megastructure
                Unlocking the celestial body will destroy the megastructure
                Different megastructures serve different purposes — check the megastructure button for details""");
        ItemTooltipManager.SHIFT.put(
            ModBlocks.SPECTRAL_ANVIL.asItem(),
            "When the upper magnet is demagnetized, a phantom shadow is created and falls downward, "
            + "it can pass through transparent blocks, and no matter the actual height, the impact is always treated as a 2‑block fall"
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.BLOCK_PLACER.asItem(), """
                When powered by redstone, this block places a block in front of it
                If struck by a falling anvil, the placement distance increases — the farther the anvil falls, the farther the block is placed
                No internal inventory and must obtain blocks from dropped items or container inventories behind it"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.SMART_BLOCK_PLACER.asItem(), """
                Advanced block placer with 5x5x5 placement area, configurable via GUI
                Supports pickup mode (from containers or drops) and move mode (direct block movement)
                Requires power supply, consumes 8 kW
                Put Structure Disk to enable Blue Print Mode, consumes 64 kW"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.STRUCTURE_SCANNER.asItem(), """
                Can store structures in Structure Disk and be used in the blueprint mode of Smart Block Placer
                Maximum can store 16×16×16 structure
                When powered by redstone, it will automatically scans and stores structures"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.FISH_TANK.asItem(), """
                It is sturdier than it looks and can be used as a substitute for the alchemy pot to perform related anvil synthesis
                Wearing it on your head provides a temporary underwater breathing effect
                Right-click the top with an item in hand to place the item inside
                Right-click the lower part of the fish tank with a tropical fish bucket in hand to release the tropical fish"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.BLOCK_DEVOURER.asItem(), """
                When powered by redstone, this block instantly breaks a 3×3 area of blocks in front of it
                If struck by a falling anvil, the breaking range increases — the farther the anvil falls, the larger the area it destroys
                No internal inventory, outputs items behind it — into containers, as dropped items, or at the break location if blocked
                Base world blocks such as stone, dirt, and deepslate drop only small amounts"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.INDUCTION_LIGHT.asItem(), """
                Provides lighting with a power consumption of 1 kW
                Right‑click with Redstone to switch to Growth Acceleration Mode
                Right‑click with Glowstone to switch to Anti‑Monster Spawning Mode
                Right‑click with Void Matter to switch to Anti‑Animal Spawning Mode
                All three special modes consume 16 kW of power"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.HELIOSTATS.asItem(), """
                Right‑click a Netherite Block or Tungsten Block with the handheld heliostat to set target block
                After placing the heliostat, it will heat the targeted block during the day, as well as the blocks above it
                Right‑click a targeted heliostat to inherit its target"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.OVERSEER.asItem(),
            "Chunk loader that works on suitable pyramid-shaped base, higher base layers provide a larger maximum load range (max 4 layers, 9x9 range), different base blocks provide different effects"
        );
        ItemTooltipManager.SHIFT.put(ModBlocks.PUMP.asItem(), """
            Provides 10 blocks of headlift on both input and output sides (including the pump itself)
            Also functions as check valve, allowing liquid to flow through only in the pump's direction
            A redstone signal disables the pump""");
        ItemTooltipManager.SHIFT.put(
            ModBlocks.CREATIVE_CRATE.asItem(), """
                Provides infinite items of a set type: place items inside to configure
                Items will not be consumed when taken out
                Destroys all input items when no item is configured
                Creative players left-click to clear the configuration
                Survival players left-click to take out items"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.CREATIVE_FLUID_TANK.asItem(), """
                Provides infinite fluid of a set type: fill fluid inside to configure
                Fluid will not be consumed when extracted
                Destroys all input fluid when no fluid is configured"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.SPACETIME_SUPERCOMPUTER.asItem(), """
                Executes commands stored in the supercomputer on a timer
                Each execution consumes power from the grid
                Acts as the computational core of the Celestial Forging Anvil"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.CELESTIAL_FORGING_ANVIL_PORTAL.asItem(), """
                Teleports players and entities between two portals
                Requires a Celestial Forging Anvil with an established wormhole connection"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.DRAIN.asItem(), """
                Draining: when more than 1 B is stored and there is space below, outputs fluid downward and fills the entire space from the bottom up
                Suction: when less than 3 B is stored and the same fluid is above, draws fluid from above and can empty the entire space above
                Does not interact with fluid at the same height; fluid can be stored for free only when it forms an infinite source"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.REDSTONE_WIRE.asItem(), """
                It can be attached to any full face of a block,
                only inputs and outputs redstone signals at its breaks (ends)
                The redstone signal level does not decay within the wire,
                and the wire will not output the signal received from redstone dust back to redstone dust"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.TRADING_STATION.asItem(), """
                Can be set to trade with players or villagers
                Villagers will actively trade with stations that have valid offers and fair prices
                Has 12 slots for temporary item storage"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.CHUTE.asItem(), """
                Can set item filter
                Shift and left-click a slot to disable it
                Use scroll wheel to set slot stack limit
                Multiple Chutes connected turn into a Simple Chute
                Simple Chute has only one slot and cannot be locked by redstone"""
        );
        ItemTooltipManager.SHIFT.put(
            ModBlocks.MAGNETIC_CHUTE.asItem(), """
                The output items will be launched with speed
                Can set item filter
                Shift and left-click a slot to disable it
                Use scroll wheel to set slot stack limit
                Multiple Magnetic Chutes connected turn into a Simple Magnetic Chute
                Simple Magnetic Chute has only one slot and cannot be locked by redstone"""
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.DRAGON_ROD.asItem(),
            "Portable block devourer, left-click to mine, right-click to adjust range, larger range costs more durability"
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.EMBER_DRAGON_ROD.asItem(),
            "Portable block devourer, left-click to mine, right-click to adjust range, larger range costs more durability"
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.FROST_DRAGON_ROD.asItem(),
            "Portable block devourer, left-click to mine, right-click to adjust range, larger range costs more durability"
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.ROYAL_DRAGON_ROD.asItem(),
            "Portable block devourer, left-click to mine, right-click to adjust range, larger range costs more durability"
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.TRANSCENDENCE_DRAGON_ROD.asItem(),
            "Portable block devourer, left-click to mine, right-click to adjust range, larger range costs more durability"
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.PILL_BOX.asItem(),
            "Store pills, right-click to take one pill each, and press [%s] to use them in the inventory"
        );
        ItemTooltipManager.SHIFT.put(
            ModItems.AMULET_BOX.asItem(), """
                Stores multiple active amulets or totems
                Right click to store the Totems of Undying on your inventory, and shift-right-click to retrieve the totems;
                When holding, consume the totems in the box when needed, and after consuming the totem, you may receive a secret gift"""
        );

        // NORMAL 优先：基础 key 使用短文本，SHIFT 仅用于 .shift key
        Map<Item, String> allTooltips = Maps.newHashMap();
        allTooltips.putAll(ItemTooltipManager.SHIFT);
        allTooltips.putAll(ItemTooltipManager.NORMAL);
        NEED_TOOLTIP_ITEMS = Collections.unmodifiableMap(allTooltips);
    }

    public static final Map<Item, String> NEED_TOOLTIP_ITEMS;

    /// 为模组物品添加工具提示
    ///
    /// @param stack   需要添加工具提示的物品堆叠
    /// @param builder 工具提示添加器
    /// @param flags   工具提示标识
    public static void addTooltip(ItemStack stack, Consumer<Component> builder, TooltipFlag flags) {
        final Item item = stack.getItem();
        if (item == ModBlocks.LENS.asItem()) {
            if (flags.hasShiftDown()) {
                builder.accept(Component.literal(
                    "Royal (cyan): drops raw ore blocks instead of raw materials, including Core Shard Ore and Void Stone"
                ).withColor(0x00FFBF));
                builder.accept(Component.literal(
                    "Frost (light blue): drops Experience Gems instead of ores, 10% chance per mined block; Core Shard Ore and Void Stone also convert to EXP"
                ).withColor(0xB4F0F6));
                builder.accept(Component.literal(
                    "Ember (yellow): drops smelted results directly; Core Shard Ore and Void Stone have no smelted form and remain unchanged"
                ).withColor(0xFFAA00));
            } else {
                ItemTooltipManager.addNormalTooltip(builder, item);
                builder.accept(ItemTooltipManager.SHIFT_TIP);
            }
        } else if (ItemTooltipManager.SHIFT.containsKey(item)) {
            // SHIFT 物品：默认显示短文本+提示，按住 Shift 显示长文本(.shift)
            if (flags.hasShiftDown()) {
                ItemTooltipManager.addShiftTooltip(builder, item);
            } else {
                if (ItemTooltipManager.NORMAL.containsKey(item)) {
                    ItemTooltipManager.addNormalTooltip(builder, item);
                }
                builder.accept(ItemTooltipManager.SHIFT_TIP);
            }
        } else if (ItemTooltipManager.NORMAL.containsKey(item)) {
            ItemTooltipManager.addNormalTooltip(builder, item);
        }
        if (stack.is(ModItemTags.REINFORCED_CONCRETE)) {
            Identifier key = BuiltInRegistries.ITEM.getKey(item);
            builder.accept(
                Component.translatable("tooltip.%s.item.reinforced_concrete".formatted(key.getNamespace()))
                    .withStyle(ChatFormatting.GRAY)
            );
        }
    }

    private static void addTranslatedTooltip(Consumer<Component> builder, String key) {
        for (String line : I18n.get(key).split("\n")) {
            builder.accept(Component.literal(line).withStyle(ChatFormatting.GRAY));
        }
    }

    private static void addNormalTooltip(Consumer<Component> builder, Item item) {
        ItemTooltipManager.addTranslatedTooltip(builder, ItemTooltipManager.getTranslationKey(item));
    }

    private static void addShiftTooltip(Consumer<Component> builder, Item item) {
        if (item == ModItems.PILL_BOX.asItem()) {
            builder.accept(Component.translatable(
                ItemTooltipManager.getTranslationKeyShift(item),
                Component.keybind("key.anvilcraft.use_pill_box")
            ).withStyle(ChatFormatting.GRAY));
            return;
        }
        ItemTooltipManager.addTranslatedTooltip(builder, ItemTooltipManager.getTranslationKeyShift(item));
    }

    public static String getTranslationKey(Item item) {
        Identifier key = BuiltInRegistries.ITEM.getKey(item);
        return "tooltip.%s.item.%s".formatted(key.getNamespace(), key.getPath());
    }

    public static String getTranslationKeyShift(Item item) {
        return ItemTooltipManager.getTranslationKey(item) + ".shift";
    }

    public static Map<Item, String> getShiftMap() {
        return Collections.unmodifiableMap(ItemTooltipManager.SHIFT);
    }
}
