package dev.dubhe.anvilcraft.api.tooltip;

import com.google.common.collect.Maps;
import dev.anvilcraft.lib.v2.util.ListUtil;
import dev.anvilcraft.lib.v2.util.Util;
import dev.dubhe.anvilcraft.block.PowerConverterBigBlock;
import dev.dubhe.anvilcraft.block.PowerConverterMiddleBlock;
import dev.dubhe.anvilcraft.block.PowerConverterSmallBlock;
import dev.dubhe.anvilcraft.client.AnvilCraftClient;
import dev.dubhe.anvilcraft.client.init.ModKeyMappings;
import dev.dubhe.anvilcraft.init.block.ModBlocks;
import dev.dubhe.anvilcraft.init.item.ModComponents;
import dev.dubhe.anvilcraft.init.item.ModFoodItems;
import dev.dubhe.anvilcraft.init.item.ModItemTags;
import dev.dubhe.anvilcraft.init.item.ModItems;
import dev.dubhe.anvilcraft.util.UnitUtil;
import net.minecraft.ChatFormatting;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.ComponentUtils;
import net.minecraft.network.chat.contents.TranslatableContents;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;

import java.util.Collections;
import java.util.List;
import java.util.Map;

public class ItemTooltipManager {

    private static final Map<Item, String> NORMAL = Maps.newHashMap();
    private static final Map<Item, String> SHIFT = Maps.newHashMap();

    static {
        NORMAL.put(ModItems.MAGNET.get(), "Attract surrounding items when use");
        NORMAL.put(ModItems.GEODE.get(), "Find the surrounding Amethyst Geode when using it");
        NORMAL.put(ModItems.ANVIL_HAMMER.get(), "It's a hammer, an anvil, a wrench, goggles, and a mace");
        NORMAL.put(ModItems.ROYAL_ANVIL_HAMMER.get(), "It's a hammer, an anvil, a wrench, goggles, and a mace");
        NORMAL.put(ModItems.EMBER_ANVIL_HAMMER.get(), "It's a hammer, an anvil, a wrench, goggles, and a mace");
        NORMAL.put(ModItems.TRANSCENDENCE_ANVIL_HAMMER.get(), "It's a hammer, an anvil, a wrench, goggles, and a mace");
        NORMAL.put(ModBlocks.CURSED_GOLD_BLOCK.asItem(), "Carriers will be cursed");
        NORMAL.put(ModItems.CURSED_GOLD_INGOT.get(), "Carriers will be cursed");
        NORMAL.put(ModItems.CURSED_GOLD_NUGGET.get(), "Carriers will be cursed");
        NORMAL.put(ModItems.TOPAZ.get(), "Containing the power of lightning");
        NORMAL.put(ModBlocks.RESIN_BLOCK.asItem(), "Use to capture friendly or weak hostile creatures LivingEntity");
        NORMAL.put(ModBlocks.CRAB_TRAP.asItem(), "Placing it in the water to help you catch aquatic products");
        NORMAL.put(ModItems.CRAB_CLAW.get(), "Increase touch length when holding");
        NORMAL.put(ModBlocks.ROYAL_ANVIL.asItem(), "Unbreakable and powerful compatibility");
        NORMAL.put(ModBlocks.ROYAL_GRINDSTONE.asItem(), "Explosion proof, Eliminating Curses and Punishing");
        NORMAL.put(ModBlocks.ROYAL_SMITHING_TABLE.asItem(), "Explosion proof, Saving your Smithing Template");
        NORMAL.put(ModBlocks.HEATER.asItem(), "Heating the block above, consumes 16 kW");
        NORMAL.put(
            ModBlocks.BURNING_HEATER.asItem(), """
                Consume fuel to heat the block above
                Each crafting consumes 240 seconds of burn time"""
        );
        NORMAL.put(ModBlocks.TRANSMISSION_POLE.asItem(), "Build a power grid with a transmission length of 8");
        NORMAL.put(ModBlocks.CHARGE_COLLECTOR.asItem(), "Collecting charges to generate power");
        NORMAL.put(ModBlocks.FE_COLLECTOR.asItem(), "Collecting FE to generate power");
        NORMAL.put(ModBlocks.PIEZOELECTRIC_CRYSTAL.asItem(), "Charge generated by an anvil fall on it");
        NORMAL.put(
            ModBlocks.MAGNET_BLOCK.asItem(),
            "Attracting the anvil below, when pushed and pulled by the piston, causes adjacent copper blocks to generate charges"
        );
        NORMAL.put(
            ModBlocks.HOLLOW_MAGNET_BLOCK.asItem(),
            "Attracting the anvil below, when pushed and pulled by the piston, causes adjacent copper blocks to generate charges"
        );
        NORMAL.put(
            ModBlocks.FERRITE_CORE_MAGNET_BLOCK.asItem(),
            "Attracting the anvil below, when pushed and pulled by the piston, causes adjacent copper blocks to generate charges"
        );
        NORMAL.put(
            ModBlocks.BATCH_CRAFTER.asItem(),
            "Received a redstone signal and crafted all internal items at once, with a power consumption of 4 kW"
        );
        NORMAL.put(
            ModBlocks.BATCH_CUTTER.asItem(),
            "Received a redstone signal and cut all internal items at once, with a power consumption of 4 kW"
        );
        NORMAL.put(ModBlocks.ROYAL_STEEL_BLOCK.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.SMOOTH_ROYAL_STEEL_BLOCK.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_ROYAL_STEEL_BLOCK.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_ROYAL_STEEL_PILLAR.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_ROYAL_STEEL_STAIRS.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_ROYAL_STEEL_SLAB.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.TEMPERING_GLASS.asItem(), "Explosion proof, No tools required on collect");
        NORMAL.put(ModBlocks.REMOTE_TRANSMISSION_POLE.asItem(), "Build a power grid with a transmission length of 16");
        NORMAL.put(ModBlocks.HEAVY_IRON_BLOCK.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.POLISHED_HEAVY_IRON_BLOCK.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.POLISHED_HEAVY_IRON_SLAB.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.POLISHED_HEAVY_IRON_STAIRS.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_HEAVY_IRON_BLOCK.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_HEAVY_IRON_SLAB.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_HEAVY_IRON_STAIRS.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.HEAVY_IRON_PLATE.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.HEAVY_IRON_COLUMN.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.HEAVY_IRON_BEAM.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.HEAVY_IRON_WALL.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.HEAVY_IRON_DOOR.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.HEAVY_IRON_TRAPDOOR.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.ITEM_COLLECTOR.asItem(), "Adjust power consumption based on range and cooling, from 2kW to 32kW");
        NORMAL.put(ModBlocks.EMBER_ANVIL.asItem(), "Wither proof");
        NORMAL.put(ModBlocks.EMBER_GRINDSTONE.asItem(), "Wither proof");
        NORMAL.put(ModBlocks.EMBER_SMITHING_TABLE.asItem(), "Wither proof");
        NORMAL.put(ModBlocks.EMBER_METAL_BLOCK.asItem(), "Wither proof");
        NORMAL.put(ModBlocks.EMBER_GLASS.asItem(), "Wither proof, No tools required on collect");
        NORMAL.put(ModBlocks.CUT_EMBER_METAL_BLOCK.asItem(), "Wither proof");
        NORMAL.put(ModBlocks.CUT_EMBER_METAL_PILLAR.asItem(), "Wither proof");
        NORMAL.put(ModBlocks.CUT_EMBER_METAL_SLAB.asItem(), "Wither proof");
        NORMAL.put(ModBlocks.CUT_EMBER_METAL_STAIRS.asItem(), "Wither proof");
        NORMAL.put(ModItems.TIN_CAN.asItem(), "Tin cans can be combined with any food to obtain canned food");
        NORMAL.put(ModFoodItems.CANNED_FOOD.asItem(), "Stackable instant food");
        NORMAL.put(ModItems.IONOCRAFT.asItem(), "It will float when placed in the power grid");
        NORMAL.put(ModItems.LEVITATION_POWDER.asItem(), "Slight weightlessness");
        NORMAL.put(ModItems.NEGATIVE_MATTER.asItem(), "Negative matter is not antimatter, it is anti gravity matter");
        NORMAL.put(ModItems.NEGATIVE_MATTER_NUGGET.asItem(), "Negative matter is not antimatter, it is anti gravity matter");
        NORMAL.put(ModBlocks.NEGATIVE_MATTER_BLOCK.asItem(), "Negative matter is not antimatter, it is anti gravity matter");
        NORMAL.put(ModItems.NEUTRONIUM_INGOT.asItem(), "Pass through most blocks except end dust, negative matter block, and bedrock");
        NORMAL.put(ModItems.STABLE_NEUTRONIUM_INGOT.asItem(), "No more passing through blocks");
        NORMAL.put(
            ModItems.CHARGED_NEUTRONIUM_INGOT.asItem(),
            "No longer passing through blocks, storing a large amount of electrical energy"
        );
        NORMAL.put(
            ModBlocks.TESLA_TOWER.asItem(),
            "Electric shock to mobs or lightning rods within a range of 8 grids, with a power consumption of 128 kW"
        );
        NORMAL.put(ModBlocks.ACTIVE_SILENCER.asItem(), "Eliminate selected nearby sounds");
        NORMAL.put(ModBlocks.COPPER_PRESSURE_PLATE.asItem(), "Redstone signal increases with pressing time, also a copper plate");
        NORMAL.put(ModBlocks.EXPOSED_COPPER_PRESSURE_PLATE.asItem(), "Redstone signal increases with pressing time, also a copper plate");
        NORMAL.put(ModBlocks.WEATHERED_COPPER_PRESSURE_PLATE.asItem(), "Redstone signal increases with pressing time, also a copper plate");
        NORMAL.put(ModBlocks.OXIDIZED_COPPER_PRESSURE_PLATE.asItem(), "Redstone signal increases with pressing time, also a copper plate");
        NORMAL.put(
            ModBlocks.ZINC_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the highest percentage of health of the mobs above, also a zinc plate"
        );
        NORMAL.put(
            ModBlocks.TIN_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the lowest percentage of health of the mobs above, also a tin plate"
        );
        NORMAL.put(
            ModBlocks.LEAD_PRESSURE_PLATE.asItem(),
            "Output redstone signal based on the number of mob species above, also a lead plate"
        );
        NORMAL.put(
            ModBlocks.SILVER_PRESSURE_PLATE.asItem(),
            "Output redstone signal based on the number of undead mobs above, also a silver plate"
        );
        NORMAL.put(
            ModBlocks.TUNGSTEN_PRESSURE_PLATE.asItem(),
            "Output redstone signal based on the number of fire-resistant entities above, also a tungsten plate"
        );
        NORMAL.put(
            ModBlocks.TITANIUM_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the highest durability of the items above, also a titanium plate"
        );
        NORMAL.put(
            ModBlocks.URANIUM_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the lowest durability of the items above, also a uranium plate"
        );
        NORMAL.put(
            ModBlocks.PLUTONIUM_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the player in hand item durability, also a plutonium plate"
        );
        NORMAL.put(
            ModBlocks.BRONZE_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on player satiety above, also a bronze plate"
        );
        NORMAL.put(
            ModBlocks.BRASS_PRESSURE_PLATE.asItem(),
            "Output a redstone signal based on the inventory's filling degree of player above, also a brass plate"
        );
        NORMAL.put(ModItems.MULTITOOL_ITEM.get(), "Press [Alt] to switch tool modes");
        NORMAL.put(ModItems.SPECTRAL_SLINGSHOT.get(), "Load a weapon to fire its phantom");
        NORMAL.put(ModItems.RECOVERY_PEARL.get(), "Right-click to teleport to last death point");
        NORMAL.put(ModBlocks.HEAT_COLLECTOR.asItem(), "Generates power from heat");
        NORMAL.put(ModBlocks.VOID_ENERGY_COLLECTOR.asItem(), "Generates power from Void energy");
        NORMAL.put(ModBlocks.RUBY_LASER.asItem(), "Emits a laser beam when powered");
        NORMAL.put(ModBlocks.RUBY_PRISM.asItem(), "Deflects or converges laser beams");
        NORMAL.put(ModBlocks.TRANSPARENT_CRAFTING_TABLE.asItem(), "Aesthetic, connectable Crafting Table");
        NORMAL.put(ModBlocks.MENGER_SPONGE.asItem(), "Absorbs infinite liquid");
        NORMAL.put(ModBlocks.SLIDING_RAIL.asItem(), "Frictionless surface for sliding entities and even blocks");
        NORMAL.put(ModBlocks.POWERED_SLIDING_RAIL.asItem(), "Accelerates items, entities, or blocks when powered");
        NORMAL.put(ModBlocks.DETECTOR_SLIDING_RAIL.asItem(), "Output signal when objects or blocks slide over");
        NORMAL.put(ModBlocks.ACTIVATOR_SLIDING_RAIL.asItem(), "Activates blocks sliding over it");
        NORMAL.put(ModBlocks.SLIDING_RAIL_STOP.asItem(), "Stops sliding items, entities, or blocks");
        NORMAL.put(ModBlocks.PROPEL_PISTON.asItem(), "Integrated piston worm, requires Capacitor or Laser power");
        NORMAL.put(ModBlocks.PULSE_GENERATOR.asItem(), "Customizes pulse delay and duration");
        NORMAL.put(ModBlocks.ADVANCED_COMPARATOR.asItem(), "Supports Hysteresis and Window comparison modes");
        NORMAL.put(ModItems.EMERALD_AMULET.get(), "Grants Hero of the Village");
        NORMAL.put(ModItems.TOPAZ_AMULET.get(), "Grants immunity to lightning damage");
        NORMAL.put(ModItems.RUBY_AMULET.get(), "Grants Fire Resistance");
        NORMAL.put(ModItems.SAPPHIRE_AMULET.get(), "Grants Conduit Power");
        NORMAL.put(ModItems.ANVIL_AMULET.get(), "Grants immunity to anvil damage");
        NORMAL.put(ModItems.FEATHER_AMULET.get(), "Grants immunity to fall damage");
        NORMAL.put(ModItems.CAT_AMULET.get(), "Scares away Creepers and Phantoms");
        NORMAL.put(ModItems.DOG_AMULET.get(), "Scares away Skeletons");
        NORMAL.put(ModItems.SILENCE_AMULET.get(), "Silences the wearer");
        NORMAL.put(
            ModItems.ABNORMAL_AMULET.get(),
            "Prevents damage from carrying Uranium, Plutonium, Floating Powder, Cursed Gold items"
        );
        NORMAL.put(ModItems.NATURE_AMULET.get(), "Combines Silence, Cat, Dog, and Feather Amulet effects");
        NORMAL.put(ModItems.GEM_AMULET.get(), "Combines effects of all four Gem Amulets");
        NORMAL.put(ModItems.CAPACITOR.asItem(), "8 MFE stored");
        NORMAL.put(ModItems.CAPACITOR_EMPTY.asItem(), "8 MFE capacity");
        NORMAL.put(ModItems.SUPER_CAPACITOR.asItem(), "160 MFE stored");
        NORMAL.put(ModItems.SUPER_CAPACITOR_EMPTY.asItem(), "160 MFE capacity");
        NORMAL.put(ModItems.ENERGY_WEAPON_PLATFORM.get(), "640 MFE stored, but will only inherit the result of Energy Weapon Making");
        NORMAL.put(ModBlocks.BLACK_HOLE.asItem(), "Dev Block with intense gravitational attraction");
        NORMAL.put(ModBlocks.WHITE_HOLE.asItem(), "Dev Block with intense gravitational repulsion");
        NORMAL.put(ModBlocks.CHARGER.asItem(), "Charges items, supports manual or automated input");
        NORMAL.put(ModBlocks.DISCHARGER.asItem(), "Discharges capacitors, supports manual or automated input");
        NORMAL.put(ModBlocks.LASER_RECEIVER.asItem(), "Generates power and output signal from received lasers");
        NORMAL.put(ModBlocks.FROST_ANVIL.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.FROST_GRINDSTONE.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.FROST_SMITHING_TABLE.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.FROST_METAL_BLOCK.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_FROST_METAL_BLOCK.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_FROST_METAL_PILLAR.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_FROST_METAL_SLAB.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.CUT_FROST_METAL_STAIRS.asItem(), "Explosion proof");
        NORMAL.put(ModBlocks.SPECTRAL_ANVIL.asItem(), "Creates phantom shadows when the upper magnet is demagnetized");
        NORMAL.put(ModBlocks.BLOCK_PLACER.asItem(), "Places blocks in front when powered by redstone");
        NORMAL.put(ModBlocks.STRUCTURE_SCANNER.asItem(), "Scans and stores structures in Structure Disk");
        NORMAL.put(ModBlocks.SMART_BLOCK_PLACER.asItem(), "Advanced block placer with 5x5x5 configurable placement area");
        NORMAL.put(ModBlocks.FISH_TANK.asItem(), "Used for anvil synthesis and provides underwater breathing when worn");
        NORMAL.put(ModBlocks.BLOCK_DEVOURER.asItem(), "Breaks 3×3 area of blocks in front when powered by redstone");
        NORMAL.put(ModBlocks.INDUCTION_LIGHT.asItem(), "Provides lighting and configurable special modes");
        NORMAL.put(ModBlocks.HELIOSTATS.asItem(), "Heats targeted blocks during the day");
        NORMAL.put(ModItems.IONOCRAFT_BACKPACK.asItem(), "Allows creative flight while equipped, requires power from the energy grid or capacitors");
        NORMAL.put(ModBlocks.BLOCK_COMPARATOR.asItem(), "Outputs signal when side blocks are the same, right-click to switch to precise state detection mode");
        NORMAL.put(ModBlocks.ITEM_DETECTOR.asItem(), "Detects specific items behind (drops/containers) to output redstone signal");
        NORMAL.put(ModBlocks.IMPACT_PILE.asItem(), "Place on Bedrock and strike with falling anvil to create Moneral Fountain");
        NORMAL.put(ModBlocks.OVERSEER_BLOCK.asItem(), "Chunk loader that works on Royal Steel base");
        NORMAL.put(ModBlocks.SPACE_OVERCOMPRESSOR.asItem(), "Compresses items into Neutronium Ingots, compresses multiblock outputs into drops");
        NORMAL.put(ModBlocks.ACCELERATION_RING.asItem(), "Creates acceleration field for anvils, projectiles, or players with Anvil Hammer");
        NORMAL.put(ModBlocks.DEFLECTION_RING.asItem(), "Deflects passing objects 90°, detect speed with Comparator");
        NORMAL.put(ModItems.DRAGON_ROD.asItem(), "Portable block devourer with adjustable range");
        NORMAL.put(ModItems.FILTER.asItem(), "Matches items based on configuration, usable in any filter slot");
        NORMAL.put(ModItems.TOTEM_OF_RECOVERY.asItem(), "Teleports to spawn on death");
        NORMAL.put(ModItems.TOTEM_OF_RAGE.asItem(), "Grants invulnerability and berserk on fatal damage");
        NORMAL.put(ModItems.COMRADE_AMULET.asItem(), "Signable by players via right-click, prevents damage from signed players");

        SHIFT.put(
            ModBlocks.SPECTRAL_ANVIL.asItem(),
            "When the upper magnet is demagnetized, a phantom shadow is created and falls downward, "
            + "it can pass through transparent blocks, and no matter the actual height, the impact is always treated as a 2‑block fall"
        );
        SHIFT.put(
            ModBlocks.BLOCK_PLACER.asItem(), """
                When powered by redstone, this block places a block in front of it
                If struck by a falling anvil, the placement distance increases — the farther the anvil falls, the farther the block is placed
                No internal inventory and must obtain blocks from dropped items or container inventories behind it"""
        );
        SHIFT.put(
            ModBlocks.STRUCTURE_SCANNER.asItem(), """
                Can store structures in Structure Disk and be used in the blueprint mode of Smart Block Placer
                Maximum can store 15×15×15 structure
                When powered by redstone, it will automatically scans and stores structures"""
        );
        SHIFT.put(
            ModBlocks.SMART_BLOCK_PLACER.asItem(), """
                Advanced block placer with 5x5x5 placement area, configurable via GUI
                Supports pickup mode (from containers) and move mode (direct block movement)
                Requires power supply, consumes 8 kW
                Put Structure Disk to enable Blue Print Mode, consumes 64 kW"""
        );
        SHIFT.put(
            ModBlocks.FISH_TANK.asItem(), """
                It is sturdier than it looks and can be used as a substitute for the alchemy pot to perform related anvil synthesis
                Wearing it on your head provides a temporary underwater breathing effect
                Right-click the top with an item in hand to place the item inside
                Right-click the lower part of the fish tank with a tropical fish bucket in hand to release the tropical fish"""
        );
        SHIFT.put(
            ModBlocks.BLOCK_DEVOURER.asItem(), """
                When powered by redstone, this block instantly breaks a 3×3 area of blocks in front of it
                If struck by a falling anvil, the breaking range increases — the farther the anvil falls, the larger the area it destroys
                No internal inventory, outputs items behind it — into containers, as dropped items, or at the break location if blocked
                Base world blocks such as stone, dirt, and deepslate drop only small amounts"""
        );
        SHIFT.put(
            ModBlocks.INDUCTION_LIGHT.asItem(), """
                Provides lighting with a power consumption of 1 kW
                Right‑click with Redstone to switch to Growth Acceleration Mode
                Right‑click with Glowstone to switch to Anti‑Monster Spawning Mode
                Right‑click with Void Matter to switch to Anti‑Animal Spawning Mode
                All three special modes consume 16 kW of power"""
        );
        SHIFT.put(
            ModBlocks.HELIOSTATS.asItem(), """
                Right‑click a Netherite Block or Tungsten Block with the handheld heliostat to set target block
                After placing the heliostat, it will heat the targeted block during the day, as well as the blocks above it"""
        );
        SHIFT.put(
            ModBlocks.OVERSEER_BLOCK.asItem(),
            "Chunk loader on 3x3 Royal Steel base, higher base layers increase chunk load range (max 3 layers, 5x5 range)"
        );
        SHIFT.put(
            ModItems.DRAGON_ROD.asItem(),
            "Portable block devourer, left-click to mine, right-click to adjust range, larger range costs more durability"
        );
        SHIFT.put(ModItems.TOTEM_OF_RECOVERY.asItem(), "Teleports to spawn on death, grants a Recall Pearl to return to death point");
        SHIFT.put(
            ModItems.TOTEM_OF_RAGE.asItem(),
            "Grants invulnerability and berserk on fatal damage, death is inevitable after 1 minute"
        );

        Map<Item, String> allTooltips = Maps.newHashMap();
        allTooltips.putAll(NORMAL);
        allTooltips.putAll(SHIFT);
        NEED_TOOLTIP_ITEMS = Collections.unmodifiableMap(allTooltips);
    }

    public static final Map<Item, String> NEED_TOOLTIP_ITEMS;

    /**
     * 为模组物品添加工具提示
     *
     * @param stack   需要添加工具提示的物品堆叠
     * @param tooltip 提示内容
     */
    public static void addTooltip(ItemStack stack, List<Component> tooltip) {
        final Item item = stack.getItem();
        if (stack.has(ModComponents.STORED_ENERGY)) {
            propertyTooltip(
                "stored_energy",
                tooltip,
                ChatFormatting.GRAY,
                UnitUtil.energyUnit(stack.getOrDefault(ModComponents.STORED_ENERGY, 0), Screen.hasShiftDown())
            );
        }
        if (stack.has(ModComponents.MULTIPHASE)) {
            if (AnvilCraftClient.CONFIG.showMultiphaseStoredId) {
                propertyTooltip(
                    "multiphase.id",
                    tooltip,
                    0xDD91FA,
                    stack.get(ModComponents.MULTIPHASE).id().toString()
                );
            }
            propertyTooltip(
                "multiphase",
                tooltip,
                0xDD91FA,
                ModKeyMappings.SWITCH_PHASE.get().getKey().getDisplayName()
            );
        }
        if (stack.has(ModComponents.PROVIDENCE)) {
            if (Screen.hasShiftDown()) {
                propertyTooltip(
                    "providence.shifting", tooltip, 0xFFCB62, ComponentUtils.formatList(
                        List.of(
                            Component.translatable("enchantment.minecraft.fortune"),
                            Component.translatable("enchantment.minecraft.looting"),
                            Component.translatable("enchantment.anvilcraft.beheading"),
                            Component.translatable("enchantment.minecraft.thorns"),
                            Component.translatable("enchantment.minecraft.luck_of_the_sea")
                        ), ComponentUtils.DEFAULT_NO_STYLE_SEPARATOR
                    )
                );
            } else {
                propertyTooltip(
                    "providence", tooltip, 0xFFCB62,
                    Minecraft.getInstance().options.keyShift.getKey().getDisplayName()
                );
            }
        }
        if (stack.has(ModComponents.ETERNAL)) {
            propertyTooltip("eternal", tooltip, 0xD3C5F6);
        }
        if (stack.has(ModComponents.FEROCIOUS)) {
            propertyTooltip("ferocious", tooltip, 0xDD1212);
        }
        if (stack.has(ModComponents.MERCILESS)) {
            propertyTooltip("merciless", tooltip, 0xB4F0F6);
        }
        if (stack.has(ModComponents.FIRE_REFORGING)) {
            propertyTooltip("fire_reforging", tooltip, ChatFormatting.GOLD);
        }
        if (SHIFT.containsKey(item)) {
            if (Screen.hasShiftDown()) {
                tooltip.add(1, getItemTooltipShift(item));
            } else {
                if (NORMAL.containsKey(item)) {
                    tooltip.add(1, getItemTooltip(item));
                }
                tooltip.add(1, Component.translatable("tooltip.anvilcraft.press_key", Component.literal("[Shift]").withStyle(ChatFormatting.WHITE)).withStyle(ChatFormatting.DARK_GRAY));
            }
        } else if (NORMAL.containsKey(item)) {
            tooltip.add(1, getItemTooltip(item));
        }
        if (stack.is(ModBlocks.POWER_CONVERTER_SMALL.asItem())) {
            tooltip.add(
                1,
                Component.translatable("tooltip.anvilcraft.item.power_converter", PowerConverterSmallBlock.INPUT_TIME)
                    .withStyle(ChatFormatting.GRAY)
            );
        }
        if (stack.is(ModBlocks.POWER_CONVERTER_MIDDLE.asItem())) {
            tooltip.add(
                1,
                Component.translatable("tooltip.anvilcraft.item.power_converter", PowerConverterMiddleBlock.INPUT_TIME)
                    .withStyle(ChatFormatting.GRAY)
            );
        }
        if (stack.is(ModBlocks.POWER_CONVERTER_BIG.asItem())) {
            tooltip.add(
                1,
                Component.translatable("tooltip.anvilcraft.item.power_converter", PowerConverterBigBlock.INPUT_TIME)
                    .withStyle(ChatFormatting.GRAY)
            );
        }
        if (stack.is(ModItemTags.REINFORCED_CONCRETE)) {
            tooltip.add(
                1,
                Component.translatable("tooltip.anvilcraft.item.reinforced_concrete")
                    .withStyle(ChatFormatting.GRAY)
            );
        }
    }

    private static Component getItemTooltip(Item item) {
        return Component.translatable(getTranslationKey(item)).withStyle(ChatFormatting.GRAY);
    }

    private static Component getItemTooltipShift(Item item) {
        return Component.translatable(getTranslationKeyShift(item)).withStyle(ChatFormatting.GRAY);
    }

    public static String getTranslationKey(Item item) {
        ResourceLocation key = BuiltInRegistries.ITEM.getKey(item);
        return "tooltip.%s.item.%s".formatted(key.getNamespace(), key.getPath());
    }

    public static String getTranslationKeyShift(Item item) {
        return getTranslationKey(item) + ".shift";
    }

    public static Map<Item, String> getNormalMap() {
        return Collections.unmodifiableMap(NORMAL);
    }

    public static Map<Item, String> getShiftMap() {
        return Collections.unmodifiableMap(SHIFT);
    }

    private static void propertyTooltip(String propertyName, List<Component> tooltip, ChatFormatting color, Object... args) {
        int i = 0;
        for (int j = 0; j < tooltip.size(); j++) {
            if (tooltip.get(j).getContents() instanceof TranslatableContents t && t.getKey().contains("enchantment")
                && ListUtil.safelyGet(tooltip, j + 1)
                    .flatMap(tooltipI -> Util.castSafely(tooltipI.getContents(), TranslatableContents.class))
                    .map(TranslatableContents::getKey)
                    .filter(key -> key.contains("enchantment"))
                    .isEmpty()
            ) {
                i = j;
                break;
            }
        }
        tooltip.add(
            1 + i,
            Component.translatable("tooltip.anvilcraft.property.%s".formatted(propertyName), args).withStyle(color)
        );
    }

    private static void propertyTooltip(String propertyName, List<Component> tooltip, int color) {
        int i = 0;
        for (int j = 0; j < tooltip.size(); j++) {
            if (tooltip.get(j).getContents() instanceof TranslatableContents t && t.getKey().contains("enchantment")
                && ListUtil.safelyGet(tooltip, j + 1)
                    .flatMap(tooltipI -> Util.castSafely(tooltipI.getContents(), TranslatableContents.class))
                    .map(TranslatableContents::getKey)
                    .filter(key -> key.contains("enchantment"))
                    .isEmpty()
            ) {
                i = j;
                break;
            }
        }
        tooltip.add(
            1 + i,
            Component.translatable("tooltip.anvilcraft.property.%s".formatted(propertyName)).withColor(color)
        );
    }

    private static void propertyTooltip(String propertyName, List<Component> tooltip, int color, Object... args) {
        int i = 0;
        for (int j = 0; j < tooltip.size(); j++) {
            if (tooltip.get(j).getContents() instanceof TranslatableContents t && t.getKey().contains("enchantment")
                && ListUtil.safelyGet(tooltip, j + 1)
                    .flatMap(tooltipI -> Util.castSafely(tooltipI.getContents(), TranslatableContents.class))
                    .map(TranslatableContents::getKey)
                    .filter(key -> key.contains("enchantment"))
                    .isEmpty()
            ) {
                i = j;
                break;
            }
        }
        tooltip.add(
            1 + i,
            Component.translatable("tooltip.anvilcraft.property.%s".formatted(propertyName), args).withColor(color)
        );
    }
}
