dependencies {
    // AnvilLib
    api(libs.anvillib)
    interfaceInjectionData(libs.anvillib.recipe)
    interfaceInjectionData(libs.anvillib.moveableEntityBlock)
    // jarJar(libs.anvillib)

    // Ageratum 藿香
    api(libs.ageratum)
    jarJar(libs.ageratum)

    // JEI
    compileClasspath(libs.jei.common.api) { transitive = false }
    compileClasspath(libs.jei.neoforge.api) { transitive = false }
    compileClasspath(libs.jei.neoforge) { transitive = false }
    runtimeClasspath(libs.jei.neoforge) { transitive = false }

    // Sodium, Iris
    compileClasspath(libs.sodium.api)
    compileClasspath(libs.sodium.mod)
    compileClasspath(libs.iris)

    // Jade
    compileClasspath(libs.jade)
    runtimeClasspath(libs.jade)
    
    // Curios API
    compileClasspath(libs.curios)
    runtimeClasspath(libs.curios)
}
