dependencies {
    // AnvilLib
    api(libs.anvillib)
    interfaceInjectionData(libs.anvillib.recipe)
    interfaceInjectionData(libs.anvillib.moveableEntityBlock)
    // jarJar(libs.anvillib)

    // JEI
    compileClasspath(libs.jei.common.api) { transitive = false }
    compileClasspath(libs.jei.forge.api) { transitive = false }
    compileClasspath(libs.jei.forge) { transitive = false }
    runtimeClasspath(libs.jei.forge) { transitive = false }

    // Sodium, Iris
    compileClasspath(libs.sodium)
    compileClasspath(libs.iris)

    // Jade
    compileClasspath(libs.jade)
}
