dependencies {
    api("com.tterrag.registrate:Registrate:${libs.versions.registrate.get()}")
    jarJar("com.tterrag.registrate:Registrate:${libs.versions.registrate.get()}")

    implementation(libs.clothConfig)

    // JEI
    compileOnlyApi(libs.jeiCommonApi) { transitive = false }
    compileOnlyApi(libs.jeiForgeApi) { transitive = false }
    implementation(libs.jeiForgeImpl) { transitive = false }

    // REI
    compileOnlyApi(libs.reiPlugin)
    compileOnlyApi(libs.reiApi)
    compileOnly(libs.reiForge)

    // EMI
    compileOnlyApi("dev.emi:emi-neoforge:${libs.versions.emi.get()}:api")
    compileOnly(libs.emi)

    // Patchouli
    compileOnlyApi("vazkii.patchouli:Patchouli:${libs.versions.patchouli.get()}:api")
    runtimeOnly(libs.patchouli)

    implementation(libs.jade)
    implementation(libs.theoneprobe)
    implementation(libs.kubejs)

    compileOnly("curse.maven:easy-npc-559312:6009031")
    //runtimeOnly("curse.maven:easy-npc-559312:6009031")
}