allprojects {
    apply plugin: 'checkstyle'
    checkstyle {
        toolVersion = '13.4.2'
        configFile = file('style.xml')
    }
    tasks.register('checkPortJava', Checkstyle) {
        source = fileTree('src/main/java') {
            include '**/*BigRedButton*.java', '**/*RedstoneDice*.java'
            include '**/client/selection/*.java', '**/mixin/client/*SelectionMixin.java', '**/mixin/client/CubeHighlightEventsMixin.java'
            include '**/PowerProducerRenderer.java', '**/AdvancedComparatorRenderer.java', '**/HeliostatsRenderer.java'
            include '**/ControlValveBlockEntityRenderer.java', '**/PipeCheckValveBERenderer.java', '**/PumpBlockEntityRenderer.java'
            include '**/OverseerBlockEntityRenderer.java', '**/WipBlockEntityRenderer.java', '**/PulseGeneratorBlockEntityRenderer.java'
            include '**/block/placement/*.java', '**/api/pointer/*.java', '**/api/block/BlockPlacementRules.java'
            include '**/api/block/IBlockPlacementRule.java', '**/api/block/ICauldron.java', '**/api/item/IBlockItem.java'
            include '**/BlockPlacementUtil.java', '**/BlockStateAndEntity.java', '**/ModBlockPlacementFallbacks.java'
            include '**/ModBlockPlacementRuleProvider.java', '**/ModTargetPointers.java', '**/FireCauldronBlock.java', '**/OilCauldronBlock.java'
            include '**/SmartBlockPlacer*.java', '**/SmartPlacer*.java', '**/StructureBookUtil.java'
            include '**/mixin/client/ItemLayerTransformInvoker.java', '**/mixin/client/ItemStackRenderStateAccessor.java'
            include '**/BlockPlacementPicking.java', '**/BlockPlaceContextMixin.java', '**/UseOnContextMixin.java', '**/ItemStackMixin.java'
            include '**/LargeBlockPlacePreviewEventListener.java', '**/ChuteBlockItem.java', '**/CelestialForgingAnvilAmplifierBlockItem.java'
            include '**/ItemSplitter*.java'
            include '**/OverflowChute*.java', '**/BaseChuteBlockEntity.java'
            include '**/IStoragePort.java', '**/StoragePortManager.java', '**/StoragePortType.java', '**/AbstractStoragePortBlock.java'
            include '**/StoragePort*.java', '**/BlockEntityItemUtil.java'
            include '**/ClientStoragePortTooltip.java'
            include '**/ScaledGuiItem*.java'
            include '**/StorageFluidPort*.java', '**/FluidBottleInteraction.java'
            include '**/FluidTankTooltip.java', '**/ClientFluidTankTooltip.java'
            include '**/api/plasma/*.java', '**/PlasmaJetsBlock*.java', '**/IEmptyCauldron.java', '**/EmptyCauldronMixin.java'
            include '**/saved/storage/category/FluidCategory.java', '**/saved/storage/category/ICategory.java'
            include '**/saved/storage/category/AndCategory.java', '**/saved/storage/category/OrCategory.java'
            include '**/saved/storage/category/NamespaceCategory.java'
            include '**/saved/storage/category/HasComponentCategory.java', '**/saved/storage/category/FilterCategory.java'
            include '**/saved/storage/category/CreativeModeTabCategory.java', '**/saved/storage/category/RecipeBookCategoryCategory.java'
            include '**/client/gui/component/category/CategoryButton.java', '**/client/gui/component/category/CategoryList.java'
            include '**/EquipmentArmorItem.java', '**/EquipmentAbilities.java', '**/AmuletAbilities.java'
            include '**/ModModelLayers.java', '**/EquipmentHelmetModel.java', '**/EquipmentClientEvents.java', '**/SwitchEquipmentAbilityPacket.java'
            include '**/EquipmentFluidOverlayMixin.java', '**/EquipmentBootsModel.java', '**/EquipmentLiquidBlockMixin.java'
            include '**/sliding/SlidingBlockInfo.java'
            include '**/AnimateAscendingBlockEntity.java', '**/SlidingBlockEntity.java', '**/CauldronOutletEntity.java'
            include '**/building/*.java'
            include '**/BuildingRodPacket.java', '**/BuildingRodResultPacket.java', '**/BuildingRodKeyboardMixin.java'
            include '**/ItemStackMixin.java', '**/BuildingRodArmedStateMixin.java'
            include '**/BuildingRodItemLayerAccessor.java', '**/ItemInHandRendererMixin.java', '**/ItemInHandRendererManager.java'
            include '**/StructureDiskData.java'
            include '**/StructureFileTransfer.java', '**/StructureBlueprintFiles.java', '**/StructureScannerFiles.java'
            include '**/StructureSaveUtil.java', '**/StructureScannerMenu.java', '**/StructureScannerBlockEntity.java'
            include '**/StructureScannerActionPacket.java'
            include '**/BuildingRodObstructionPacket.java', '**/BuildingRodObstructionGlowMixin.java'
            include '**/LargeCakeBlock.java', '**/LargeCakeBlockItem.java'
            include '**/BuildingRodItem.java', '**/StoredEnergyEmptyProperty.java', '**/BuildingRodLang.java'
            include '**/BlueprintUndoChunkMixin.java', '**/BlueprintEntityDropsMixin.java', '**/BlueprintTntOriginMixin.java'
            include '**/BlueprintLevelMixin.java', '**/BlueprintServerLevelMixin.java', '**/BlueprintTicksMixin.java'
            include '**/BlueprintBlockEventsAccessor.java'
            include '**/InWorldRecipeEventListener.java', '**/MeshRecipe.java', '**/UnpackRecipe.java', '**/ItemCrushRecipe.java'
            include '**/ProcessingItemStackRenderer.java', '**/ProcessingModel*.java'
            include '**/*ProcessingTable*.java', '**/StampingPlatform*.java', '**/CrushingTable*.java', '**/SiftingTable*.java', '**/UnpackingTable*.java'
            include '**/UseItemOnBlock.java', '**/ProcessingTablePlacement.java', '**/ModBlockPlacementRuleProvider.java'
            include '**/BlockItemHandlerPointer.java', '**/ItemEntityPointer.java'
            include '**/ItemDetectorBlockEntity.java', '**/PulseGeneratorBlockEntity.java'
            include '**/WheelGuiBlurMixin.java', '**/GuiBlurBoundaryAccessor.java', '**/WheelWidgetMixin.java'
            include '**/WheelBackgroundCapture.java', '**/WheelBackgroundFrameMixin.java', '**/WheelFrostedBackgroundMixin.java'
            include '**/LensBlock.java'
            include '**/WheelLifecycleEventListener.java'
            include '**/DragonRodItem.java', '**/SwitchDragonRodProtectContainersPacket.java', '**/DevourUtil.java'
            include '**/DevouringLevelReader.java', '**/BlockDevourerBlock.java'
            include '**/ResonanceMiningClientEventListener.java', '**/ItemDefaultComponentsEventListener.java', '**/Multiphase.java'
            include '**/TranscendenceHeavyHalberdItem.java', '**/TranscendenceAnvilHammerItem.java'
            include '**/ResonatorItem.java', '**/TranscendenceResonatorItem.java', '**/ResonatorItemTypeMixin.java'
            include '**/WeaponChargeProgressPacket.java'
            include '**/EnergyWeapon*.java', '**/EnergyReload*.java', '**/SpectralWeaponLauncherItem.java'
            include '**/ICapacitorChargeable.java', '**/IFullCapacitor.java', '**/WeatherproofChestplate*.java'
            include '**/EquipmentChestModel.java', '**/EquipmentPoweredProperty.java', '**/EquipmentLayerTextureMixin.java'
            include '**/IonoCraftBackpackItem.java', '**/IonoCraftBackpackToggleDescentPacket.java'
            include '**/IonoCraftBackpackClientHandler.java', '**/CapacitorItem.java', '**/SuperCapacitorItem.java'
            include '**/BufferBootsChargeHUD.java', '**/Pocket*.java', '**/CreativePocket*.java'
            include '**/EquipmentLeggingsModel.java', '**/EquipmentPocketLockMixin.java', '**/SlotPositionAccessor.java'
            include '**/ArmorSlotMixin.java', '**/InventoryMenuMixin.java', '**/JeiPocketEffectAreaMixin.java', '**/SwapPocketPacket.java'
            include '**/Atmosphere*.java', '**/ModLevelKeys.java', '**/GravityManager.java'
            include '**/EntityMixin.java', '**/ItemEntityMixin.java', '**/ExperienceOrbMixin.java', '**/FallingBlockEntityMixin.java'
            include '**/projectile/AbstractArrowMixin.java', '**/projectile/AbstractHurtingProjectileMixin.java', '**/projectile/ThrowableProjectileMixin.java'
            include '**/api/amulet/AmuletManager.java', '**/item/property/component/amulet/*.java', '**/Comrades.java'
            include '**/ComradeAmuletItem.java', '**/ModAmulets.java', '**/BoxContents.java'
            include '**/BoxSelection*.java', '**/PillSelectorSupport.java', '**/AmuletSelectorSupport.java'
            include '**/client/event/ClientEventListener.java'
            include '**/BundleLike*.java', '**/InvertedActionEventListener.java', '**/PillBoxItem.java', '**/AmuletBoxItem.java'
            include '**/PillBoxContents.java', '**/event/PlayerTickEventHandler.java'
            include '**/data/lang/CategoryLang.java'
            include '**/ReadOnlyItemResourceHandler.java', '**/ModCapabilities.java'
            include '**/recipe/frost/*.java', '**/FrostSmithingMenu.java', '**/FrostSmithingTransfer.java', '**/FrostRecipeTransferHandler.java', '**/FrostSmithingCategory.java', '**/SpiderMixin.java'
            include '**/FrostSmithingScreen.java', '**/SmithingPreview.java', '**/PermutationTemplateItem.java', '**/DeformationRecipeLoader.java'
            include '**/PermutationRecipeLoader.java', '**/FrostSmithingPackets.java', '**/ModFrostMaterialPredicateTypes.java', '**/ModMathFunctions.java'
            include '**/AdjacentSmithingMenu.java', '**/EmberSmithingMenu.java', '**/TranscendenceSmithingMenu.java'
            include '**/SmithingServerStub.java', '**/SmithingRecipeTransferHandler.java', '**/JeiSmithingTransferMixin.java'
            include '**/MultipleToOneSmithingCategory.java'
            include '**/TerminalSnapshotLoader.java', '**/TerminalJei*.java', '**/JeiBasicRecipeTransferHandlerMixin.java'
            include '**/TerminalInsertionDecoration.java', '**/event/TooltipEventListener.java', '**/client/AnvilCraftClient.java'
            include '**/TerminalReachabilityCache.java', '**/TerminalRemoteOverlay.java', '**/TerminalOverlayEventListener.java'
            include '**/TerminalKeyMappingEventListener.java', '**/ModKeyMappings.java', '**/KeyMappingLang.java'
            include '**/PlayerBalanceHandler.java', '**/TerminalBalanceModePacket.java'
            include '**/TerminalUpgradeRecipe.java', '**/TerminalUnbindRecipe.java', '**/data/lang/MessageLang.java'
            include '**/TerminalSessions.java', '**/TerminalItem.java', '**/*TerminalItem.java', '**/TerminalBinding.java'
            include '**/StorageTerminal*Stub.java', '**/BalanceMode.java', '**/HyperdimensionStorageStationBlock.java'
            include '**/TerminalSourceManager.java', '**/block/entity/storage/StorageBlockEntity.java'
            include '**/event/LevelEventListener.java', '**/event/ServerLifecycleEventListener.java'
            include '**/StorageRecipeTransferPlan.java', '**/StorageJeiBridge.java', '**/StorageJeiSupport.java'
            include '**/StorageSetting.java', '**/SettingClientStub.java', '**/SettingServerStub.java', '**/CategorySettingsScreen.java'
            include '**/StorageServerStub.java', '**/StorageClientStub.java', '**/StorageInput.java', '**/StorageScreen.java', '**/StorageMenu.java'
            include '**/FluidAmountUtil.java'
            include '**/StructureLoadUtil.java', '**/StructureDisk*Packet.java', '**/StructureDiskPreviewSupport.java'
            include '**/item/utility/DiskItem.java', '**/StructureDiskData.java'
            include '**/recipe/multiblock/Multiblock*.java', '**/IMultiblockRecipe.java', '**/LevelLikeDisplaySupport.java'
            include '**/GiantAnvilLandingEventListener.java'
            include '**/BlockStatePredicateMixin.java'
            include '**/FittedItemRenderer.java', '**/FilterItemRenderer.java', '**/DiskItemRenderer.java', '**/DiskDisplaySupport.java'
            include '**/FormattingUtil.java', '**/ItemResourceHelper.java'
            include '**/unlimited/UnlimitedItemStacksResourceHandler.java'
            include '**/saved/storage/*Storage.java'
        } + fileTree('dev/porting/java')
        classpath = files()
        maxWarnings = 0
        reports {
            xml.required = true
            html.required = true
        }
    }
}
