[versions]
minecraft = "26.1.2"
neoForge = "26.1.2.75"
jei = "29.6.2.31"
jade = "26.1.1+neoforge"
modDevGradle = "2.0.141"
lombok = "8.7.1"
machete = "1.2.0"
anvillib = "2.0.0+snapshot.494"
ageratum = "0.0.1+build.109"
sodium = "0.9.1+mc26.1.2"
iris = "1.10.9+26.1-neoforge"
curios = "15.0.0+26.1.2"

[libraries]
jei-common-api = { group = "mezz.jei", name = "jei-26.1.2-common-api", version.ref = "jei" }
jei-neoforge-api = { group = "mezz.jei", name = "jei-26.1.2-neoforge-api", version.ref = "jei" }
jei-neoforge = { group = "mezz.jei", name = "jei-26.1.2-neoforge", version.ref = "jei" }
sodium-api = {  group = "net.caffeinemc", name = "sodium-neoforge-api", version.ref = "sodium"}
sodium-mod = {  group = "net.caffeinemc", name = "sodium-neoforge-mod", version.ref = "sodium"}
iris = {  group = "maven.modrinth", name = "iris", version.ref = "iris"}
jade = { group = "maven.modrinth", name = "jade", version.ref = "jade" }
curios = { group = "top.theillusivec4.curios", name = "curios-neoforge", version.ref = "curios" }
anvillib-recipe = { group = "dev.anvilcraft.lib", name = "anvillib-recipe-neoforge-26.1", version.ref = "anvillib" }
anvillib-moveableEntityBlock = { group = "dev.anvilcraft.lib", name = "anvillib-moveable-entity-block-neoforge-26.1", version.ref = "anvillib" }
anvillib = { group = "dev.anvilcraft.lib", name = "anvillib-neoforge-26.1", version.ref = "anvillib" }
ageratum = { group = "dev.anvilcraft.resource", name = "ageratum-neoforge-26.1.2", version.ref = "ageratum" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
machete = { id = "io.github.p03w.machete", version.ref = "machete" }
