name: Feature request - 功能请求
description: Suggest an idea for this project - 为这个项目推荐一个新想法
title: "[Feature] "
labels:
  - 🪁 enhancement

body:
  - type: markdown
    attributes:
      value: |
        Before filling in this `issue`, please make sure that there are no similar or duplicate `issues` that have been opened.
        填写此 `issue` 前，请先确认已经开启的 `issue` 没有类似或重复的 `issue`。

  - type: textarea
    attributes:
      label: What new features do you want? - 你想要什么新功能？
      description: |
        What new feature or change you want? How it improves? Please tell us the requirements is with a clear and detailed description, put your screenshots if possible.
        你想要什么新功能或者什么改变？这会带来什么提升？请清晰而详细地描述你的需求，如果可以的话最好附带截图。
    validations:
      required: true

  - type: checkboxes
    id: know
    attributes:
      label: Checks - 检查项
      options:
        - label: I have searched the [issue tracker](https://github.com/Anvil-Dev/AnvilCraft/issues) and confirmed that there is no identical issue. 我已经搜索[问题追踪器](https://github.com/Anvil-Dev/AnvilCraft/issues)并且确认没有相同的 Issue。
          required: true
        - label: I admit that I previously checked all options without thorough verification and directly submitted this Issue, and I agree that it can be closed directly. 我承认此前未充分核实便勾选了所有选项并直接提交此 Issue ，且同意该 Issue 可被直接关闭。
        - label: I confirm that I am currently using the latest snapshot or LTS version of AnvilCraft. If not, this issue can be closed directly. 我确认当前使用的是铁砧工艺的最新快照版本或 LTS 版本，若非如此，此 Issue 可被直接关闭。
          required: true
        - label: I promise to provide a detailed description of the new feature I want, along with reasonable justification, rather than offering incomplete or vague information. 我承诺我会详细描述我想要的新功能，并附上合理的理由，而非提供不完整或模糊的信息。
          required: true
