plugins {
    id 'java-library'
    id 'maven-publish'
    alias libs.plugins.modDevGradle
    alias libs.plugins.lombok
    alias libs.plugins.machete
}

neoForge {
    version = libs.versions.neoForge.get()

    parchment {
        minecraftVersion = "1.21.1"
        mappingsVersion = libs.versions.parchment.get()
    }
}
apply from: "$rootDir/gradle/scripts/repositories.gradle"

machete {
    // disable machete locally for faster builds
    enabled = false
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)