@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.dubhe.anvilcraft.inventory;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;