package dev.dubhe.anvilcraft.init.item.tabs;

import dev.anvilcraft.lib.v2.registrum.util.CreativeTabSection;
import dev.anvilcraft.lib.v2.registrum.util.CreativeTabSections;
import dev.dubhe.anvilcraft.AnvilCraft;
import dev.dubhe.anvilcraft.init.block.ModBlocks;
import dev.dubhe.anvilcraft.init.item.ModItems;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.Items;

public class FunctionalBlocksSections extends DisplayItemsGenerator {
    @Override
    public void accept() {
        if (!(this.output instanceof CreativeTabSections sections)) {
            return;
        }
        sections.section(
            CreativeTabSection.builder(
                    AnvilCraft.of("textures/gui/creative_inventory/section/functional_blocks/forging.png")
                )
                .textAlignment(CreativeTabSection.TextAlignment.LEFT)
                .textIndent(17)
                .text(Component.translatable("anvilcraft.creative.section.functional_blocks.forging"))
                .build(),
            content -> {
                content.accept(Items.ANVIL);
                content.accept(Items.CHIPPED_ANVIL);
                content.accept(Items.DAMAGED_ANVIL);
                content.accept(ModBlocks.NEOFORGE);
                content.accept(ModBlocks.SPECTRAL_ANVIL);
                content.accept(ModBlocks.ROYAL_ANVIL);
                content.accept(ModBlocks.FROST_ANVIL);
                content.accept(ModBlocks.EMBER_ANVIL);
                content.accept(ModBlocks.TRANSCENDENCE_ANVIL);
                content.accept(ModBlocks.GIANT_ANVIL);
                content.accept(ModBlocks.ROYAL_GRINDSTONE);
                content.accept(ModBlocks.FROST_GRINDSTONE);
                content.accept(ModBlocks.EMBER_GRINDSTONE);
                content.accept(ModBlocks.TRANSCENDENCE_GRINDSTONE);
                content.accept(ModBlocks.ROYAL_SMITHING_TABLE);
                content.accept(ModBlocks.FROST_SMITHING_TABLE);
                content.accept(ModBlocks.EMBER_SMITHING_TABLE);
                content.accept(ModBlocks.TRANSCENDENCE_SMITHING_TABLE);
            }
        );
        sections.section(
            CreativeTabSection.builder(
                    AnvilCraft.of("textures/gui/creative_inventory/section/functional_blocks/processing.png")
                )
                .textAlignment(CreativeTabSection.TextAlignment.LEFT)
                .textIndent(17)
                .text(Component.translatable("anvilcraft.creative.section.functional_blocks.processing"))
                .build(),
            content -> {
                content.accept(ModBlocks.MAGNET_BLOCK);
                content.accept(ModBlocks.HOLLOW_MAGNET_BLOCK);
                content.accept(ModBlocks.FERRITE_CORE_MAGNET_BLOCK);
                content.accept(Items.IRON_TRAPDOOR);
                content.accept(Items.CAMPFIRE);
                content.accept(Items.STONECUTTER);
                content.accept(Items.SCAFFOLDING);
                content.accept(ModBlocks.STAMPING_PLATFORM);
                content.accept(ModBlocks.CRUSHING_TABLE);
                content.accept(ModBlocks.SIFTING_TABLE);
                content.accept(ModBlocks.UNPACKING_TABLE);
                content.accept(Items.CAULDRON);
                content.accept(ModBlocks.LARGE_CAULDRON);
                content.accept(ModBlocks.FISH_TANK);
                content.accept(ModBlocks.CORRUPTED_BEACON);
                content.accept(ModBlocks.NEUTRON_IRRADIATOR);
                content.accept(ModBlocks.BURNING_HEATER);
                content.accept(ModBlocks.HEATER);
            }
        );
        sections.section(
            CreativeTabSection.builder(
                    AnvilCraft.of("textures/gui/creative_inventory/section/functional_blocks/logistics.png")
                )
                .textAlignment(CreativeTabSection.TextAlignment.LEFT)
                .textIndent(17)
                .text(Component.translatable("anvilcraft.creative.section.functional_blocks.logistics"))
                .build(),
            content -> {
                content.accept(ModBlocks.CRATE);
                content.accept(ModBlocks.LARGE_CRATE);
                content.accept(ModBlocks.SHULKER_CONTAINER);
                content.accept(ModBlocks.HYPERDIMENSION_STORAGE_STATION);
                content.accept(ModBlocks.CHUTE);
                content.accept(ModBlocks.MAGNETIC_CHUTE);
                content.accept(ModBlocks.SLIDING_RAIL);
                content.accept(ModBlocks.POWERED_SLIDING_RAIL);
                content.accept(ModBlocks.ACTIVATOR_SLIDING_RAIL);
                content.accept(ModBlocks.DETECTOR_SLIDING_RAIL);
                content.accept(ModBlocks.SLIDING_RAIL_STOP);
            }
        );
        sections.section(
            CreativeTabSection.builder(
                    AnvilCraft.of("textures/gui/creative_inventory/section/functional_blocks/fluid_trans.png")
                )
                .textAlignment(CreativeTabSection.TextAlignment.LEFT)
                .textIndent(17)
                .text(Component.translatable("anvilcraft.creative.section.functional_blocks.fluid_trans"))
                .build(),
            content -> {
                content.accept(ModBlocks.MENGER_SPONGE);
                content.accept(ModBlocks.FLUID_TANK);
                content.accept(ModBlocks.LARGE_FLUID_TANK);
                content.accept(ModBlocks.DRAIN);
                content.accept(ModItems.PIPE);
                content.accept(ModItems.GLASS_PIPE);
                content.accept(ModBlocks.PUMP);
                content.accept(ModBlocks.CONTROL_VALVE);
                content.accept(ModItems.CHECK_VALVE);
            }
        );
        sections.section(
            CreativeTabSection.builder(
                    AnvilCraft.of("textures/gui/creative_inventory/section/functional_blocks/functional.png")
                )
                .textAlignment(CreativeTabSection.TextAlignment.LEFT)
                .textIndent(17)
                .text(Component.translatable("anvilcraft.creative.section.functional_blocks.functional"))
                .build(),
            content -> {
                content.accept(ModBlocks.CRAB_TRAP);
                content.accept(ModBlocks.ACTIVE_SILENCER);
                content.accept(ModBlocks.JEWEL_CRAFTING_TABLE);
                content.accept(ModBlocks.TRADING_STATION);
                content.accept(ModBlocks.BLOCK_PLACER);
                content.accept(ModBlocks.BLOCK_DEVOURER);
                content.accept(ModBlocks.TRANSPARENT_CRAFTING_TABLE);
                content.accept(ModBlocks.SPACE_OVERCOMPRESSOR);
                content.accept(ModBlocks.OVERSEER_BLOCK);
                content.accept(ModBlocks.IMPACT_PILE);
                content.accept(ModBlocks.MINERAL_FOUNTAIN);
                content.accept(ModBlocks.RESIN_BLOCK);
                content.accept(ModBlocks.AMBER_BLOCK);
                content.accept(ModBlocks.MOB_AMBER_BLOCK);
                content.accept(ModBlocks.RESENTFUL_AMBER_BLOCK);
            }
        );
        sections.section(
            CreativeTabSection.builder(
                    AnvilCraft.of("textures/gui/creative_inventory/section/functional_blocks/power.png")
                )
                .textAlignment(CreativeTabSection.TextAlignment.LEFT)
                .textIndent(17)
                .text(Component.translatable("anvilcraft.creative.section.functional_blocks.power"))
                .build(),
            content -> {
                content.accept(ModBlocks.MAGNETO_ELECTRIC_CORE_BLOCK);
                content.accept(ModBlocks.PIEZOELECTRIC_CRYSTAL);
                content.accept(ModBlocks.HELIOSTATS);
                content.accept(ModBlocks.TRANSMISSION_POLE);
                content.accept(ModBlocks.REMOTE_TRANSMISSION_POLE);
                content.accept(ModBlocks.LOAD_MONITOR);
                content.accept(ModBlocks.CHARGE_COLLECTOR);
                content.accept(ModBlocks.HEAT_COLLECTOR);
                content.accept(ModBlocks.VOID_ENERGY_COLLECTOR);
                content.accept(ModBlocks.INFINITE_COLLECTOR);
                content.accept(ModBlocks.FE_COLLECTOR);
                content.accept(ModBlocks.POWER_CONVERTER_SMALL);
                content.accept(ModBlocks.POWER_CONVERTER_MIDDLE);
                content.accept(ModBlocks.POWER_CONVERTER_BIG);
                content.accept(ModBlocks.POWER_CONVERTER_SUPER_BIG);
                content.accept(ModBlocks.POWER_CONVERTER_EXTREMELY_BIG);
                content.accept(ModBlocks.INDUCTION_LIGHT);
                content.accept(ModBlocks.CHARGER);
                content.accept(ModBlocks.DISCHARGER);
                content.accept(ModBlocks.TESLA_TOWER);
                content.accept(ModBlocks.BATCH_CRAFTER);
                content.accept(ModBlocks.BATCH_CUTTER);
                content.accept(ModBlocks.ITEM_COLLECTOR);
                content.accept(ModBlocks.EXP_COLLECTOR);
                content.accept(ModBlocks.AUTO_ENCHANTING_TABLE);
                content.accept(ModBlocks.RUBY_LASER);
                content.accept(ModBlocks.RUBY_PRISM);
                content.accept(ModBlocks.LARGE_LASER);
                content.accept(ModBlocks.LENS);
                content.accept(ModBlocks.LASER_RECEIVER);
                content.accept(ModBlocks.SMART_BLOCK_PLACER);
                content.accept(ModBlocks.STRUCTURE_SCANNER);
                content.accept(ModBlocks.PROPEL_PISTON);
                content.accept(ModBlocks.ACCELERATION_RING);
                content.accept(ModBlocks.DEFLECTION_RING);
            }
        );
        sections.section(
            CreativeTabSection.builder(
                    AnvilCraft.of("textures/gui/creative_inventory/section/functional_blocks/redstone.png")
                )
                .textAlignment(CreativeTabSection.TextAlignment.LEFT)
                .textIndent(17)
                .text(Component.translatable("anvilcraft.creative.section.functional_blocks.redstone"))
                .build(),
            content -> {
                content.accept(ModBlocks.PULSE_GENERATOR);
                content.accept(ModBlocks.ADVANCED_COMPARATOR);
                content.accept(ModBlocks.BLOCK_COMPARATOR);
                content.accept(ModBlocks.ITEM_DETECTOR);
                content.accept(ModBlocks.REDSTONE_WIRE);
                content.accept(ModBlocks.CONTROLLABLE_SAND);
                content.accept(ModBlocks.COPPER_PRESSURE_PLATE);
                content.accept(ModBlocks.EXPOSED_COPPER_PRESSURE_PLATE);
                content.accept(ModBlocks.WEATHERED_COPPER_PRESSURE_PLATE);
                content.accept(ModBlocks.OXIDIZED_COPPER_PRESSURE_PLATE);
                content.accept(ModBlocks.TUNGSTEN_PRESSURE_PLATE);
                content.accept(ModBlocks.TITANIUM_PRESSURE_PLATE);
                content.accept(ModBlocks.ZINC_PRESSURE_PLATE);
                content.accept(ModBlocks.TIN_PRESSURE_PLATE);
                content.accept(ModBlocks.LEAD_PRESSURE_PLATE);
                content.accept(ModBlocks.SILVER_PRESSURE_PLATE);
                content.accept(ModBlocks.URANIUM_PRESSURE_PLATE);
                content.accept(ModBlocks.PLUTONIUM_PRESSURE_PLATE);
                content.accept(ModBlocks.BRASS_PRESSURE_PLATE);
                content.accept(ModBlocks.BRONZE_PRESSURE_PLATE);
            }
        );
        sections.section(
            CreativeTabSection.builder(
                AnvilCraft.of("textures/gui/creative_inventory/section/functional_blocks/cfa.png")
                )
                .textAlignment(CreativeTabSection.TextAlignment.LEFT)
                .textIndent(17)
                .text(Component.translatable("anvilcraft.creative.section.functional_blocks.cfa"))
            .build(),
            content -> {
                content.accept(ModBlocks.CONFINEMENT_CHAMBER);
                content.accept(ModBlocks.CONFINED_TIME_ANVILON);
                content.accept(ModBlocks.CONFINED_SPACE_ANVILON);
                content.accept(ModBlocks.CONFINED_MASS_ANVILON);
                content.accept(ModBlocks.CONFINED_ENERGY_ANVILON);
                content.accept(ModBlocks.CONFINED_NEUTRONIUM_INGOT_BLOCK);
                content.accept(ModBlocks.SPACETIME_SUPERCOMPUTER);
                content.accept(ModBlocks.MASS_ENERGY_INVERTER);
                content.accept(ModBlocks.CELESTIAL_FORGING_ANVIL);
                content.accept(ModBlocks.CELESTIAL_FORGING_ANVIL_AMPLIFIER);
                content.accept(ModBlocks.CELESTIAL_FORGING_ANVIL_LOGISTICS_INTERFACE);
                content.accept(ModBlocks.CELESTIAL_FORGING_ANVIL_FLUID_INTERFACE);
                content.accept(ModBlocks.CELESTIAL_FORGING_ANVIL_LASER_INTERFACE);
                content.accept(ModBlocks.CELESTIAL_FORGING_ANVIL_PORTAL);
                content.accept(ModBlocks.CELESTIAL_FORGING_ANVIL_INTERFACE_PLACEHOLDER);
            }
        );
        sections.section(
            CreativeTabSection.builder(
                AnvilCraft.of("textures/gui/creative_inventory/section/functional_blocks/creative.png")
                )
                .textAlignment(CreativeTabSection.TextAlignment.LEFT)
                .textIndent(17)
                .text(Component.translatable("anvilcraft.creative.section.functional_blocks.creative"))
            .build(),
            content -> {
                content.accept(ModBlocks.CREATIVE_GENERATOR);
                content.accept(ModBlocks.CREATIVE_LASER);
                content.accept(ModBlocks.CREATIVE_FLUID_TANK);
                content.accept(ModBlocks.CREATIVE_CRATE);
                content.accept(ModBlocks.BLACK_HOLE);
                content.accept(ModBlocks.WHITE_HOLE);
            }
        );
    }
}
