name: Pull Request GameTest
on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: zulu
          java-version: 17

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Fabric GameTest
        run: ./gradlew anvilcraft-fabric:runGameTestServer

      - name: Run Forge GameTest
        run: ./gradlew anvilcraft-forge:runGameTestServer
